import { create } from 'zustand';

export type Locale = 'en' | 'zh' | 'ja';

const translations: Record<Locale, Record<string, string>> = {
  en: {
    "briefTitle": "Build something from scratch",
    "briefDescription": "Describe your idea. AI will work through the requirements and prepare a development prompt for you to review.",
    "briefIdeaLabel": "Your software idea",
    "briefPlaceholder": "What should it do, who is it for, and what matters most? Add any features, platforms, or design preferences you already have in mind.",
    "briefInputHint": "Enter to generate · Shift+Enter for a new line",
    "briefGenerate": "Think through my idea",
    "briefRegenerate": "Generate again",
    "briefThinking": "Working through requirements, edge cases, and acceptance criteria…",
    "briefOutputTitle": "Development prompt · editable",
    "briefFolderHint": "Creates a new folder under ~/ConeCode Projects/ when you start.",
    "briefOutputHint": "Enter to start · Shift+Enter to edit on a new line",
    "briefCopy": "Copy prompt",
    "briefCopied": "Copied",
    "briefStart": "Start building",
    "briefStarting": "Starting…",
    "briefGenerateFailed": "Could not generate a complete prompt. Check your model connection and try again.",
    "briefFolderFailed": "Could not create or open the project folder. Check folder permissions and retry.",
    "briefConversationChanged": "You switched conversations while preparing the project. Return here to start again.",
    "briefStartFailed": "Could not start the project. Your prompt is still available to copy or retry.",
    "briefCopyFailed": "Copy failed. Select the prompt and copy it manually.",
    // Sidebar
    'newChat': 'New Chat',
    'sidebarNoProject': 'No project',
    'sidebarFiles': 'Files',
    'installHolding': 'Installing — model paused, will continue when done',
    'installContinue': 'Installs finished. Activate and continue the work you were doing.',
    'settings': 'Settings',
    'language': 'Language',
    // Chat
    'typeMessage': 'Type a message...',
    // Agent home ("find me something to do")
    'homeGreetingMorning': 'Morning — what should we work on?',
    'homeGreetingAfternoon': 'Afternoon — what should we work on?',
    'homeGreetingEvening': 'Evening — what should we work on?',
    'homeGreetingNight': 'Still up? What should we work on?',
    'homeClean': 'clean tree',
    'homeFiles': 'files',
    'homeScripts': 'scripts',
    'homeRescan': 'Re-read the project',
    'homeNoFolder': 'No folder open yet',
    'homeUncommitted': 'uncommitted',
    'homeNoTests': 'no tests',
    'homeFindWork': 'Work I found for you',
    'homeFindWorkAction': 'Find work',
    'homeRefindWork': 'Find again',
    'homeFindFailed': 'Could not work out what to do',
    'homeIdleTitle': 'Let me look through the project',
    'homeIdleBody': 'I will read the git state, TODO comments, tests and scripts, then propose concrete tasks you can start with one click.',
    'homeOpenFolderTitle': 'Open a project first',
    'homeOpenFolderBody': 'Once a folder is open I can read its state and suggest what to do next — or scaffold a brand-new project for you.',
    'homeResume': 'Pick up where you left off',
    'homeContinue': 'Continue',
    'homeOpenOnly': 'Just open',
    'homeOpenTodos': 'left to do',
    'homeStartNew': 'Start something new',
    // The recommended next action
    'recLabel': 'Do this next',
    'recResume': 'Finish what you started — items still open:',
    'recReview': 'Review your uncommitted changes — files changed:',
    'recTask': 'Start the top task I found:',
    'recTests': 'This project has no tests — add the first one',
    'recTestsPrompt': 'This project has no tests. Pick the most important behaviour, set up the project\'s standard test runner if it is missing, and write one real test for it. Run it and show me it passes.',
    'recStart': 'Open a project, or pick one below and I will build it',
    'recStartNew': 'Everything is clean — pick something new to build',
    'recDialogInputAria': 'Next action message',
    'recDialogPlaceholder': 'Edit the suggested instruction, or write your own. Enter to start.',
    'recDialogStartPlaceholder': 'Describe what to build, or leave empty to pick a project below…',
    'recDialogHint': 'Enter to start · Shift+Enter for a new line',
    'recDialogSend': 'Start',
    'recDialogBrowseIdeas': 'Browse ideas',
    // Autopilot
    'autopilotTitle': 'Pick one — I build it',
    'autopilotSubtitle': 'folder, code, tests, all on my own',
    'autopilotThinking': 'thinking of ideas…',
    'autopilotFrom': 'ideas from',
    'autopilotMore': 'Other ideas',
    'autopilotMedium': 'bigger',
    'autopilotCreating': 'Creating the project folder',
    'autopilotBuilding': 'Building it',
    'autopilotVerifying': 'Running it to check it works',
    'autopilotRepairing': 'Fixing what failed',
    'autopilotRepairingHint': 'It did not pass yet — fixing and re-running. Attempt',
    'autopilotDone': 'Done and verified',
    'autopilotDoneHint': 'The project was built and its tests pass.',
    'autopilotOpenReadme': 'Open README',
    'autopilotFailed': 'Could not finish',
    'autopilotFailedHint': 'It still does not pass after several attempts. The conversation has the full history — tell it what to do next.',
    'autopilotNoVerify': 'It never reported a command to verify the project with.',
    'autopilotNoFolder': 'Could not create the project folder.',
    'homeNewProject': 'New project',
    'homeNewProjectDesc': 'Describe an idea and I will scaffold it, working, with a test.',
    'homeNewProjectHint': 'Describe what you want to build. I will pick the stack, scaffold it, and prove it runs.',
    'homeNewProjectPlaceholder': 'e.g. a CLI that watches a folder and compresses new images',
    'homeNewProjectNeedsDir': 'I will ask you where to put it.',
    'homeCreate': 'Build it',
    'homeOpenFolderDesc': 'Work on code that already exists.',
    'homeExplore': 'Explore this codebase',
    'homeExploreDesc': 'Get an architecture tour of what is here.',
    'homeExplorePrompt': 'Give me a tour of this codebase: what it does, how it is structured, the entry points, and the three things I most need to know before editing it. Read enough of the real files to be accurate.',
    'homeReview': 'Review my changes',
    'homeReviewDesc': 'Check the uncommitted work for problems.',
    'homeReviewPrompt': 'Review my uncommitted changes with git status and git diff. Look for real defects, edge cases and inconsistencies with the surrounding code, and tell me what you would fix first. Do not change anything yet.',
    'justNow': 'just now',
    'minutesAgoShort': 'm ago',
    'hoursAgoShort': 'h ago',
    'daysAgoShort': 'd ago',
    'taskKind_bug': 'Bug',
    'taskKind_feature': 'Feature',
    'taskKind_refactor': 'Refactor',
    'taskKind_test': 'Tests',
    'taskKind_docs': 'Docs',
    'taskKind_chore': 'Chore',
    'taskEffort_quick': 'Quick',
    'taskEffort_medium': 'Medium',
    'taskEffort_large': 'Large',
    'taskRisk_low': 'low risk',
    'taskRisk_medium': 'some risk',
    'taskRisk_high': 'risky',
    'selectModelHint': 'Select a model and type a message',
    'dismiss': 'Dismiss',
    'ai': 'AI',
    // Model Selector
    'searchModels': 'Search models...',
    'selectModel': 'Select Model',
    'noModels': 'No models found',
    'favorites': 'Favorites',
    'recent': 'Recent',
    // Model Tooltip
    'textChat': 'Text Chat',
    'vision': 'Vision',
    'imageGen': 'Image Gen',
    'audioIn': 'Audio In',
    'audioOut': 'Audio Out',
    'functions': 'Functions',
    'context': 'Context',
    'maxOutput': 'Max Output',
    'contextWindow': 'Context Window',
    'editLimits': 'Edit limits',
    'readFromApi': 'Read from API',
    'reset': 'Reset',
    // Context Meter
    'contextUsage': 'Context Usage',
    'contextLeft': 'context left',
    'used': 'Used',
    'remaining': 'Remaining',
    'compactions': 'Compactions',
    'tokens': 'tokens',
    'messages': 'Messages',
    'attachedFiles': 'Attached files',
    'systemPrompt': 'System prompt',
    'estimated': 'estimated',
    'attachFiles': 'Attach files',
    // Provider Settings
    'providerSettings': 'Provider Settings',
    'setGeneral': 'General',
    'setGeneralDesc': 'How much the agent may do on its own, and how it is confined.',
    'setProviders': 'Providers',
    'setProvidersDesc': 'API endpoints and keys. Detect a provider\'s models after entering its URL and key.',
    'setMcpDesc': 'Connect MCP servers to give the agent extra tools.',
    'addProvider': 'Add Provider',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'cancel': 'Cancel',
    'save': 'Save',
    'cannotPreview': 'Cannot preview this file',
    'delete': 'Delete',
    'providerName': 'Provider Name',
    'baseUrl': 'Base URL',
    'apiKey': 'API Key',
    'defaultModel': 'Default Model',
    'timeout': 'Timeout (ms)',
    'default': 'Default',
    'none': 'None',
    'custom': 'Custom',
    'openFolder': 'Open Folder',
    'closeFolder': 'Close Folder',
    'closeFile': 'Close File',
    'refresh': 'Refresh',
    'enableReasoning': 'Enable Reasoning',
    'disableReasoning': 'Disable Reasoning',
    'lightMode': 'Light Mode',
    'darkMode': 'Dark Mode',
    'reasoning': 'Reasoning',
    // Code Review
    'codeReview': 'Code Review',
    'pending': 'pending',
    'applied': 'Applied',
    'reverted': 'Reverted',
    'pendingChanges': 'Pending Changes',
    'appliedChanges': 'Applied Changes',
    'revertedChanges': 'Reverted Changes',
    'apply': 'Apply',
    'reject': 'Reject',
    'applyAll': 'Apply all',
    'rejectAll': 'Reject all',
    'autoApproveAll': 'Auto-approve all (experimental)',
    'autoApproveWarning': 'Risky: the AI will run commands and apply file changes automatically, without asking for your confirmation.',
    'errNoContent': 'The model returned no content. It may have only produced reasoning, or the response was cut off. Try retrying, lowering thinking effort, or raising the model\'s max output tokens.',
    'errTruncated': 'The model hit its max output token limit before finishing (often truncated mid-reasoning). Raise the model\'s max output tokens or lower the thinking effort, then retry.',
    'revert': 'Revert',
    'revertFailed': 'Revert failed',
    'close': 'Close',
    'commandExecution': 'Command Execution',
    'pendingApproval': 'Pending Approval',
    'reviewCommand': 'Review',
    'workingDirectory': 'Working directory',
    'commandApprovalHint': 'Check the command and working directory before running it. Its effects may not be reversible.',
    'commandFailed': 'The command failed.',
    'changeFailed': 'Failed',
    'from': 'From:',
    'to': 'To:',
    'source': 'Source:',
    'destination': 'Destination:',
    'result': 'Result:',
    'execute': 'Execute',
    'read': 'Read',
    'list': 'List',
    'search': 'Search',
    'find': 'Find',
    'edit': 'Edit',
    'send': 'Send',
    'editMessagePlaceholder': 'Edit message...',
    'create': 'Create',
    'newFolder': 'New folder',
    'rename': 'Rename',
    'copy': 'Copy',
    'run': 'Run',
    'openApp': 'Open app',
    'open': 'Open',
    'systemInfo': 'System info',
    'question': 'Question',
    'thinking': 'Thinking',
    'writing': 'Writing',
    // Message bubble
    'toolResult': 'Tool result',
    'you': 'You',
    'aiAsking': 'AI is asking',
    'typeAnswerHint': 'Type your answer in the input below and send',
    'answered': 'Answered',
    // Chat input send hints
    'sendHintEnter': 'Enter to send · Shift+Enter for newline',
    'sendHintCmd': 'Cmd/Ctrl+Enter to send',
    // Thinking effort levels
    'effortFast': 'Fast',
    'effortAuto': 'Auto · picks depth from your ask',
    'previewAnnotate': 'Pin a spot for precise edit',
    'previewAnnotateHint': 'Click the page to pin coordinates · fills the chat',
    'previewAnnotateClear': 'Clear pins',
    'modePlan': 'Plan',
    'modeTask': 'Task',
    'modeOrchestrate': 'Orchestrate',
    'modeRsi': 'RSI',
    'modeMenu': 'Modes & extras',
    'effortBalanced': 'Balanced',
    'effortDeep': 'Deep',
    // Slash commands
    'commandsTitle': 'Commands',
    'cmdHelp': 'Show available commands',
    'cmdClear': 'Start a new chat',
    'cmdCompact': 'Summarize & free up context',
    'cmdPlan': 'Toggle Plan Mode (read-only planning)',
    'cmdGoal': 'Start or replace a long-running goal',
    'cmdMode': 'Set agent mode: standard | goal | orchestrate | rsi',
    'agentModeStandard': 'Standard',
    'agentModeStandardHint': 'Default coding loop — one request, end to end.',
    'agentModeGoal': 'Goal',
    'agentModeGoalHint': 'Long-running goal pursuit until external completion checks pass.',
    'agentModeOrchestrate': 'Orchestrate',
    'agentModeOrchestrateHint': 'Conductor + sub-agents: decompose, research in parallel, integrate.',
    'agentModeRsi': 'RSI+RL',
    'agentModeRsiHint': 'RL-style search toward the frozen goal: sample, score with an orchestrated judge panel, accept only if reward beats best, stop at plateau.',
    'cmdReview': 'Review Git changes without modifying them',
    'cmdWorktree': 'Manage isolated Git worktrees',
    'cmdInit': 'Analyze the project and write AGENTS.md',
    'cmdAgents': 'Open the AGENTS.md project memory',
    'cmdModel': 'Switch model',
    'cmdMemory': 'Show what I remember about you',
    'cmdDiff': 'Summarize the current git diff',
    'cmdCommit': 'Stage changes and commit',
    'helpTitle': 'ConeCode commands',
    'helpProjectCommands': 'Project commands',
    'noAgentsMd': 'No AGENTS.md found yet — run /init to create one.',
    'goalRunning': 'Goal running',
    'goalPaused': 'Goal paused',
    'pauseGoal': 'Pause goal',
    'resumeGoal': 'Resume goal',
    'editGoal': 'Edit goal',
    'clearGoal': 'Clear goal',
    'goalResumePrompt': 'Resume the active goal. Re-check current progress and continue until its completion criteria are verified.',
    'goalUpdatedPrompt': 'The active goal has been updated. Use this as the new completion criteria:',
    'reviewReadOnly': 'Prioritized findings · read-only',
    'reviewUncommitted': 'Review uncommitted changes',
    'reviewUncommittedHint': 'Includes staged, unstaged, and untracked paths in the current checkout.',
    'reviewBase': 'Review against a base branch',
    'reviewBaseHint': 'Reviews the branch diff from the merge base to HEAD.',
    'reviewCommit': 'Review a commit',
    'reviewCommitHint': 'Reviews exactly one commit by SHA, tag, or revision.',
    'reviewCommitPlaceholder': 'Commit SHA or revision',
    'reviewNeedsRepo': 'Open a project inside a Git repository to start a review.',
    'reviewReadFailed': 'Could not read the selected Git change set.',
    'reviewNoChanges': 'There are no changes in this review scope.',
    'reviewPreparing': 'Preparing review…',
    'startReview': 'Start read-only review',
    'worktrees': 'Worktrees',
    'worktreesHint': 'Run parallel tasks in isolated Git checkouts.',
    'worktreeName': 'Task name (optional)',
    'createWorktree': 'Create isolated worktree',
    'worktreeNeedsRepo': 'Open a Git repository to use worktrees.',
    'worktreeLoadFailed': 'Could not load Git worktrees.',
    'worktreeCreateFailed': 'Could not create the worktree.',
    'worktreeOpenFailed': 'Could not open the worktree folder.',
    'worktreeRemoveFailed': 'Could not remove the worktree.',
    'detachedHead': 'Detached HEAD',
    'current': 'Current',
    'localCheckout': 'primary checkout',
    'uncommitted': 'uncommitted',
    'removeWorktreeConfirm': 'Remove this clean managed worktree?',
    'compacting': 'Compacting…',
    'contextCompacted': 'Context compacted',
    'compactFailed': 'Could not compact the conversation.',
    'compact': 'Compact',
    'showCompacted': 'Show compacted messages',
    'hideCompacted': 'Hide compacted messages',
    // Plan mode
    'planMode': 'Plan Mode',
    'plan': 'Plan',
    'planModeHint': 'Read-only — the agent researches and proposes a plan before editing.',
    'presentPlan': 'Plan ready',
    'approvePlan': 'Approve & run',
    'keepPlanning': 'Keep planning',
    'planApproved': 'Plan approved — implement it now.',
    'planBlocked': 'Blocked in Plan Mode (read-only). Present a plan instead.',
    // To-dos
    'todos': 'To-dos',
    'todoUpdated': 'To-do list updated.',
    'deleteTodo': 'Remove this item',
    'clearTodos': 'Clear the checklist',
    'expandTodos': 'Show the full checklist',
    'collapseTodos': 'Hide the full checklist',
    'allTodosCompleted': 'All tasks completed',
    // Rollback
    'undoChange': 'Undo change',
    'undoChangeConfirmTitle': 'Undo only this workspace change?',
    'undoChangeKeepsChat': 'The conversation stays. The agent will be told that the workspace changed.',
    'rollbackConversation': 'Roll back chat',
    'checkpointRollbackTitle': 'Roll back to this conversation checkpoint?',
    'checkpointRollbackChat': 'This message and everything after it will be removed; reversible file changes will be restored.',
    'checkpointExternalEffects': 'Executed commands and computer actions remain in effect and stay marked as applied.',
    'confirmCheckpointRollback': 'Roll back checkpoint',
    'checkpointUnavailable': 'This change has no conversation checkpoint.',
    // Approval modes
    'approvalMode': 'Approval',
    'approvalSuggest': 'Suggest',
    'approvalAutoEdit': 'Auto-edit',
    'approvalFullAuto': 'Full-auto',
    'approvalSuggestDesc': 'Ask before every edit and command (safest).',
    'approvalAutoEditDesc': 'Auto-apply file edits; ask before running commands.',
    'approvalFullAutoDesc': 'Auto-apply edits and run commands without asking (risky).',
    // Tool-call protocol
    'toolCallMode': 'Tool calls',
    'toolModeAuto': 'Auto',
    'toolModeNative': 'Native',
    'toolModePrompt': 'Prompt',
    'toolModeAutoDesc': 'Use the provider\'s function calling when the model supports it (recommended).',
    'toolModeNativeDesc': 'Always send tool schemas — for endpoints that support tools but don\'t advertise them.',
    'toolModePromptDesc': 'Never send tool schemas; ask for ```json actions in the prompt instead.',
    'callingTool': 'Calling',
    // Command sandbox
    'sandbox': 'Command sandbox',
    'sandboxOn': 'Confined',
    'sandboxOff': 'Unrestricted',
    'sandboxOnDesc': 'Commands can read your machine and only write inside the workspace (and temp). Recommended.',
    'sandboxOffDesc': 'Commands run with your full permissions and can modify anything on this machine.',
    'sandboxNetwork': 'Allow network access (needed for installs)',
    'sandboxUnavailable': 'Command sandboxing is only available on macOS; commands run unrestricted here.',
    'notifications': 'Notifications',
    'notificationsDesc': 'Get an OS notification when a task finishes or needs attention.',
    'notification_never': 'Never',
    'notification_background': 'In background',
    'notification_always': 'Always',
    'notifyApprovals': 'Notify when an action needs approval',
    'preventSleepWhileRunning': 'Prevent app suspension while a task is running',
    'taskReadyTitle': 'Task ready',
    'taskReadyBody': 'ConeCode finished the current turn.',
    'approvalReadyTitle': 'Approval needed',
    'approvalReadyBody': 'ConeCode is waiting for you to review an action.',
    // Memory
    'memory': 'Memory',
    'memoryEnabled': 'On',
    'memoryHint': 'What ConeCode has learned: how you want work done, what is true about this project, and how you like to be talked to. Applied to every new conversation.',
    'memoryEmpty': 'Nothing learned yet. Memories are picked up automatically as you work.',
    'memoryAdd': 'Add',
    'memoryAddPlaceholder': 'Teach it something, e.g. "Always answer in Chinese"',
    'memoryForget': 'Forget this',
    'memoryClear': 'Forget everything',
    'memoryClearConfirm': 'Delete all memories?',
    'memoryProjectOnly': 'this project',
    'memoryStyle': 'Communication style',
    'memoryWorkflow': 'How to work',
    'cmdAddDir': 'Open another folder alongside this one',
    'addFolder': 'Add folder',
    'removeFolder': 'Close this folder',
    'addedFolder': 'Folder added',
    'addFolder_duplicate': 'That folder is already open.',
    'addFolder_inside-existing': 'That folder is already inside an open one.',
    'addFolder_contains-existing': 'That folder contains folders that are already open — close them first.',
    'captureWhere': 'Remember this — where does it belong?',
    'captureProject': 'This project',
    'captureUser': 'Every project',
    'memoryFilesTitle': 'Memory files in effect',
    'memoryScope_user': 'yours, every project',
    'memoryScope_ancestor': 'inherited from a parent folder',
    'memoryScope_project': 'this project',
    'memoryNoFiles': 'No memory files yet — start one with "# your rule".',
    'memoryOpenHint': 'Open one with /memory project or /memory user. Capture a new rule by starting a message with "# ".',
    'memoryNoSuchFile': 'No memory file matches that.',
    'memoryProject': 'About this project',
    'memoryLearned': 'learned',
    'memoryAddProjectPlaceholder': 'A fact about this codebase, e.g. "Pure logic lives in src/core"',
    'memoryProjectNeedsFolder': 'Open a folder first — a project memory needs a project to belong to.',
    'memoryCodeIssue': 'Recurring code problem',
    'memoryFact': 'Fact',
    'memoryTitle': 'What I remember about you',
    'memoryNone': 'I have not learned anything about you yet.',
    // @ mentions
    'mentionFiles': 'Attach a file',
    // Git
    'gitBranch': 'Branch',
    'gitClean': 'clean',
    // Web + MCP + sub-agents
    'fetchWeb': 'Fetch URL',
    'searchWeb': 'Web search',
    'downloadFile': 'Download',
    'subAgent': 'Sub-agent',
    'mcpTool': 'MCP tool',
    'mcpServers': 'MCP Servers',
    // Skills (plugin library)
    'skills': 'Skills',
    'skillsHint': 'Reusable expertise the agent loads when a task calls for it. Deploy one to this project or to every project.',
    'skillLibrary': 'Library',
    'skillDeploy': 'Deploy',
    'skillProjectShort': 'Project',
    'skillDeployGlobal': 'Deploy for every project',
    'skillDeployProject': 'Deploy to this project only',
    'skillNeedsProject': 'Open a project first to deploy a skill into it.',
    'skillRemove': 'Remove',
    'skillEnable': 'Enable',
    'skillDisable': 'Disable',
    'skillDisabled': 'disabled',
    'skillShadowedBadge': 'overridden',
    'skillShadowedTip': 'A project skill with the same id overrides this global skill.',
    'skillOpen': 'Open SKILL.md',
    'skillGlobal': 'Available in every project',
    'skillProject': 'This project only',
    'useSkill': 'Skill',
    // Custom skills
    'skillNew': 'New skill',
    'skillEdit': 'Edit',
    'skillImport': 'Import file',
    'skillImportError': 'That file is not a usable SKILL.md.',
    'skillCustomBadge': 'custom',
    'skillCustomTip': 'You wrote or imported this. ConeCode does not review custom skills.',
    'skillGlobalShort': 'All projects',
    'skillExists': 'A skill with this name already exists in that scope.',
    'skillNamePlaceholder': 'Name, e.g. House Style',
    'skillDescPlaceholder': 'When should the AI use this?',
    'skillDescHint': 'This one line is all the AI sees until it decides to load the skill — say when to use it.',
    'skillBodyPlaceholder': 'The instructions. Markdown. Be specific about what to do and what not to do.',
    'skillNameError': 'A name is required.',
    'skillDescError': 'A description is required (max 200 characters).',
    'skillBodyError': 'Write the actual instructions (at least a sentence).',
    'skillRiskTitle': 'Custom skills run on your responsibility',
    'skillRiskBody': 'A skill is instructions the AI will follow, and it can tell the AI to edit files, run commands, or fetch from the network. ConeCode does not review or sandbox the text of a skill. Only install skills you wrote or fully trust — anything you add here, and whatever comes of it, is on you.',
    'skillRiskStillApplies': 'Your approval mode and the command sandbox still apply to anything a skill actually does.',
    'skillRiskAccept': 'I understand — I accept responsibility',
    'gitStatus': 'Git status',
    'gitDiff': 'Git diff',
    'thinkingTime': 'Thinking time',
    // Terminal
    'terminal': 'Terminal',
    'terminals': 'Terminals',
    'newTerminal': 'New terminal',
    'renameTerminal': 'Rename terminal',
    // Live preview (built-in browser)
    'preview': 'Preview',
    'previewStart': 'Start preview',
    'previewStop': 'Stop',
    'previewRestart': 'Restart',
    'previewStarting': 'Starting…',
    'previewRunning': 'Running',
    'previewIdle': 'Not running',
    'previewFailed': 'Preview failed',
    'previewBack': 'Back',
    'previewForward': 'Forward',
    'previewStopLoading': 'Stop loading',
    'previewOpenExternal': 'Open in browser',
    'previewDesktop': 'Desktop',
    'previewTablet': 'Tablet',
    'previewMobile': 'Phone',
    'previewLogs': 'Output',
    'previewClearLogs': 'Clear output',
    'previewNoOutput': 'No output yet',
    'previewNoFolder': 'No project open',
    'previewNoFolderHint': 'Open a folder and I can run it and show the result right here.',
    'previewNotDetectedHint': 'No dev script or index.html found. Type the command that starts this project, or a port to open.',
    'previewCustomCommand': 'Custom command',
    'previewAddressPlaceholder': 'Type a URL',
    'previewNewTab': 'New tab',
    'previewOpen': 'Open',
    'previewStaticFiles': 'Static files',
    'previewCommandPlaceholder': 'Command that starts this project',
    'previewOrTypeUrl': 'Or type any address above',
    'previewPick': 'Pick an element',
    'previewPickHint': 'Click any element to send it to the chat · Esc to cancel',
    'previewPickedElement': 'About this element:',
    'previewRetry': 'Retry',
    'previewExited': 'The preview process exited',
    'unsaved': 'Unsaved',
    // Computer control (the agent drives the real screen)
    'computerControl': 'Computer control',
    'computerActive': 'The agent can use your mouse and keyboard',
    'computerInactive': 'Off — the agent cannot touch the screen',
    'computerUnsupported': 'Computer control is only available on macOS and Windows.',
    'computerWarnTitle': 'This hands over your machine',
    'computerWarnBody': 'While this is on, the agent can see your screen and click and type anywhere — including apps that are not ConeCode. Turn it off when you are done.',
    'computerEnable': 'Let the agent control this computer',
    'computerDisable': 'Agent is controlling this computer',
    'computerSessionOnly': 'For this session only — always off at launch',
    'computerStopNow': 'Stop and take back control',
    'computerPermissions': 'macOS permissions',
    'computerAccessibility': 'Accessibility',
    'computerAccessibilityHint': 'Needed to move the pointer and type. Without it macOS discards the events silently.',
    'computerScreenRecording': 'Screen Recording',
    'computerScreenRecordingHint': 'Needed to take screenshots. Grant it in System Settings › Privacy & Security.',
    'computerGranted': 'Granted',
    'computerOpenSettings': 'Open Settings',
    'computerRestartHint': 'macOS only applies a newly granted permission after the app restarts.',
    'computerApproval': 'Approval',
    'computerApprovalAsk': 'Each click and keystroke is shown for your approval first. Switch the approval mode to Full auto to let them run unattended.',
    'computerApprovalAuto': 'Approval mode is Full auto, so actions run without asking. Watch the log below.',
    'computerScreen': 'Screen',
    'computerAsSeen': 'as the model sees it',
    'computerLastShot': 'What the agent last saw',
    'computerActivity': 'Activity',
    'computerNoActivity': 'Nothing yet',
    // Model auto-detect
    'detectModels': 'Detect models',
    'detecting': 'Detecting…',
    'modelsFound': 'models detected',
    'detectFailed': 'Detection failed',
    'detectHint': 'Enter Base URL + API Key, then auto-detect available models and their context windows.',
    // Changed files panel
    'panels': 'Panels',
    'panelsMore': 'More tools',
    'openFile': 'Open file…',
    'changedFiles': 'Changed files',
    'filesChanged': 'files changed',
    'noChanges': 'No changes to show',
    // Remote control (phone)
    'remoteControl': 'Remote control',
    'remoteDesc': 'Drive ConeCode from your phone over Wi-Fi or the internet.',
    'scanToConnect': 'Scan to connect',
    'lanAddress': 'On the same Wi-Fi',
    'publicLink': 'Public link (内网穿透)',
    'startServer': 'Start',
    'stopServer': 'Stop',
    'serverOnline': 'Online',
    'serverOff': 'Off',
    'serverStarting': 'Starting…',
    'tunnelStarting': 'Opening tunnel…',
    'tunnelHint': 'cloudflared is built in, so this usually needs no setup. If it keeps failing, check your network, or use ngrok (needs a free account + authtoken).',
    'devicesConnected': 'connected',
    'remotePassword': 'Password',
    'remotePasswordPlaceholder': 'Optional — leave blank for none',
    'remotePasswordHint': 'When set, the password is embedded in the QR so scanning connects automatically. Keep the QR private.',
    'tunnelMethod': 'Tunnel method',
    'tunnelCloudflare': 'Cloudflare (built-in, no account)',
    'tunnelCustom': 'Custom command',
    'auto': 'Auto (nearest)',
    'tunnelCustomHint': 'Use {url} or {port} as placeholders; the command must print a public https:// URL.',
    'remotePasswordReq': 'Must be ≥6 chars with an uppercase letter, a number, and a symbol.',
    'remotePublicNeedsPassword': 'Set a password above to enable the public link.',
    'tunnelNotInstalled': 'Tunnel tool not found. Cloudflare is built in; ngrok must be installed (e.g. brew install ngrok) and given an authtoken.',
    'tunnelTimeout': 'Timed out establishing the tunnel — the network may block it. Retry or switch method.',
    'tunnelFailed': 'The tunnel failed to start. See the tool output below (and ~/.conecode-tunnel.log).',
    'ngrokHint': 'Get a free authtoken at ngrok.com. No ngrok installed? Use the one-click install below.',
    'ngrokInstall': 'One-click install ngrok',
    'cfdAdaptiveHint': 'Downloads the matching cloudflared for this computer (macOS / Windows) automatically.',
    'cfdInstall': 'One-click install cloudflared',
    'cfdInstalling': 'Installing cloudflared…',
    'cfdInstalled': 'cloudflared installed. Open the public link.',
    'cfdInstallFailed': 'cloudflared install failed',
    'ngrokInstalling': 'Installing ngrok…',
    'ngrokInstalled': 'ngrok installed. Fill the authtoken and open the public link.',
    'ngrokInstallFailed': 'ngrok install failed',
    'connectedDevices': 'Connected devices',
    'kickDevice': 'Kick',
    'noDevices': 'No devices connected.',
    'copyLink': 'Copy link',
    'copied': 'Copied',
  },
  zh: {
    "briefTitle": "从一个想法，开始做软件",
    "briefDescription": "说说你想做的软件。AI 会梳理需求、明确范围，整理成一份可直接开发的 Prompt。",
    "briefIdeaLabel": "你的软件思路",
    "briefPlaceholder": "例如：我想做一个给自由职业者用的记账软件，能记录收支、按项目统计利润，界面简洁，数据保存在本地。",
    "briefInputHint": "Enter 生成 Prompt · Shift+Enter 换行",
    "briefGenerate": "梳理需求并生成",
    "briefRegenerate": "重新生成",
    "briefThinking": "正在梳理需求、边界条件和验收标准…",
    "briefOutputTitle": "开发 Prompt · 可编辑",
    "briefFolderHint": "开始后会在 ~/ConeCode Projects/ 下自动新建独立文件夹。",
    "briefOutputHint": "Enter 开始工作 · Shift+Enter 换行编辑",
    "briefCopy": "复制 Prompt",
    "briefCopied": "已复制",
    "briefStart": "开始工作",
    "briefStarting": "正在启动…",
    "briefGenerateFailed": "未能生成完整 Prompt，请检查模型连接后重试。",
    "briefFolderFailed": "无法创建或打开项目文件夹，请检查目录权限后重试。",
    "briefConversationChanged": "准备项目期间切换了对话，已停止启动，请返回这里重试。",
    "briefStartFailed": "项目启动失败，Prompt 已保留，可复制或重试。",
    "briefCopyFailed": "复制失败，请选中 Prompt 手动复制。",
    'newChat': '新对话',
    'sidebarNoProject': '无项目',
    'sidebarFiles': '文件',
    'installHolding': '安装中 — 模型已暂停，完成后自动继续',
    'installContinue': '安装完成。激活模型并继续之前的工作。',
    'settings': '设置',
    'language': '语言',
    'typeMessage': '输入消息...',
    // Agent home ("找点活干")
    'homeGreetingMorning': '早上好，今天做点什么？',
    'homeGreetingAfternoon': '下午好，接下来做点什么？',
    'homeGreetingEvening': '晚上好，今晚做点什么？',
    'homeGreetingNight': '还没睡？想做点什么？',
    'homeClean': '工作区干净',
    'homeFiles': '个文件',
    'homeScripts': '个脚本',
    'homeRescan': '重新读取项目',
    'homeNoFolder': '还没有打开文件夹',
    'homeUncommitted': '个未提交',
    'homeNoTests': '没有测试',
    'homeFindWork': '我给你找到的活',
    'homeFindWorkAction': '找点活干',
    'homeRefindWork': '重新找',
    'homeFindFailed': '没能想出该做什么',
    'homeIdleTitle': '让我先看看这个项目',
    'homeIdleBody': '我会读取 git 状态、TODO 注释、测试和脚本，然后给出可以一键开始的具体任务。',
    'homeOpenFolderTitle': '先打开一个项目',
    'homeOpenFolderBody': '打开文件夹后，我就能读取它的状态并建议接下来做什么 —— 或者直接为你搭建一个全新项目。',
    'homeResume': '继续上次的工作',
    'homeContinue': '继续完成',
    'homeOpenOnly': '仅打开',
    'homeOpenTodos': '项待完成',
    'homeStartNew': '开始新的',
    // The recommended next action
    'recLabel': '接下来做这个',
    'recResume': '先把没做完的做完 —— 还剩',
    'recReview': '审查未提交的改动 —— 改动文件数：',
    'recTask': '从我找到的最优先任务开始：',
    'recTests': '这个项目还没有测试 —— 先补第一个',
    'recTestsPrompt': '这个项目还没有测试。挑最重要的一个行为，如果缺少测试框架就先配好，然后写一个真正有意义的测试。运行它并把通过结果给我看。',
    'recStart': '打开一个项目，或者从下面选一个我来做',
    'recStartNew': '一切都很干净 —— 挑个新东西来做',
    'recDialogInputAria': '下一步操作消息',
    'recDialogPlaceholder': '可修改建议指令，或自己写一条。回车开始。',
    'recDialogStartPlaceholder': '描述你想做什么，或留空去下面挑一个项目…',
    'recDialogHint': 'Enter 开始 · Shift+Enter 换行',
    'recDialogSend': '开始',
    'recDialogBrowseIdeas': '浏览点子',
    // Autopilot
    'autopilotTitle': '选一个，我来做',
    'autopilotSubtitle': '建文件夹、写代码、跑通，全程不用管',
    'autopilotThinking': '正在想点子…',
    'autopilotFrom': '来自',
    'autopilotMore': '换一批',
    'autopilotMedium': '稍大',
    'autopilotCreating': '正在创建项目文件夹',
    'autopilotBuilding': '正在开发',
    'autopilotVerifying': '正在实际运行验证',
    'autopilotRepairing': '正在修复问题',
    'autopilotRepairingHint': '还没跑通，正在修复后重跑。第',
    'autopilotDone': '已完成并验证通过',
    'autopilotDoneHint': '项目已经建好，测试真实通过。',
    'autopilotOpenReadme': '打开 README',
    'autopilotFailed': '没能完成',
    'autopilotFailedHint': '多次尝试后仍未跑通。完整过程都在对话里，你可以直接告诉它下一步怎么做。',
    'autopilotNoVerify': '它没有给出用于验证项目的命令。',
    'autopilotNoFolder': '无法创建项目文件夹。',
    'homeNewProject': '新建项目',
    'homeNewProjectDesc': '说出你的想法，我来搭好架子、写出能跑的代码和一个测试。',
    'homeNewProjectHint': '描述你想做什么。我会选好技术栈、搭建项目，并验证它真的能跑起来。',
    'homeNewProjectPlaceholder': '例如：一个监听文件夹并自动压缩新图片的命令行工具',
    'homeNewProjectNeedsDir': '我会先问你放在哪里。',
    'homeCreate': '开始搭建',
    'homeOpenFolderDesc': '在已有的代码上继续工作。',
    'homeExplore': '摸清这个代码库',
    'homeExploreDesc': '快速了解这里都有什么、怎么组织的。',
    'homeExplorePrompt': '带我了解这个代码库：它做什么、如何组织、入口在哪，以及在动手改之前我最需要知道的三件事。请真的读足够多的文件，保证准确。',
    'homeReview': '审查我的改动',
    'homeReviewDesc': '检查未提交的代码有没有问题。',
    'homeReviewPrompt': '用 git status 和 git diff 审查我未提交的改动。找出真正的缺陷、边界情况，以及和周围代码不一致的地方，并告诉我你会先修哪一个。现在先不要改代码。',
    'justNow': '刚刚',
    'minutesAgoShort': '分钟前',
    'hoursAgoShort': '小时前',
    'daysAgoShort': '天前',
    'taskKind_bug': '缺陷',
    'taskKind_feature': '功能',
    'taskKind_refactor': '重构',
    'taskKind_test': '测试',
    'taskKind_docs': '文档',
    'taskKind_chore': '杂项',
    'taskEffort_quick': '很快',
    'taskEffort_medium': '中等',
    'taskEffort_large': '较大',
    'taskRisk_low': '低风险',
    'taskRisk_medium': '有风险',
    'taskRisk_high': '高风险',
    'selectModelHint': '选择模型并输入消息',
    'dismiss': '关闭',
    'ai': 'AI',
    'searchModels': '搜索模型...',
    'selectModel': '选择模型',
    'noModels': '未找到模型',
    'favorites': '收藏',
    'recent': '最近使用',
    'textChat': '文本对话',
    'vision': '图片识别',
    'imageGen': '图片生成',
    'audioIn': '音频输入',
    'audioOut': '音频输出',
    'functions': '函数调用',
    'context': '上下文',
    'maxOutput': '最大输出',
    'contextWindow': '上下文长度',
    'editLimits': '编辑上下文/输出',
    'readFromApi': '从 API 读取',
    'reset': '重置',
    'contextUsage': '上下文用量',
    'contextLeft': '剩余上下文',
    'used': '已用',
    'remaining': '剩余',
    'compactions': '压缩次数',
    'tokens': 'tokens',
    'messages': '对话消息',
    'attachedFiles': '附加文件',
    'systemPrompt': '系统提示',
    'estimated': '估算值',
    'attachFiles': '上传文件',
    'providerSettings': '提供商设置',
    'setGeneral': '通用',
    'setGeneralDesc': 'AI 可以自己做多少事，以及它受到怎样的限制。',
    'setProviders': '服务商',
    'setProvidersDesc': 'API 地址与密钥。填好后可自动检测该服务商的模型。',
    'setMcpDesc': '连接 MCP 服务器，为 AI 提供额外工具。',
    'addProvider': '添加提供商',
    'enabled': '已启用',
    'disabled': '已禁用',
    'cancel': '取消',
    'save': '保存',
    'cannotPreview': '无法预览此文件',
    'delete': '删除',
    'providerName': '提供商名称',
    'baseUrl': '基础 URL',
    'apiKey': 'API 密钥',
    'defaultModel': '默认模型',
    'timeout': '超时时间 (ms)',
    'default': '默认',
    'none': '无',
    'custom': '自定义',
    'openFolder': '打开文件夹',
    'closeFolder': '关闭文件夹',
    'closeFile': '关闭文件',
    'refresh': '刷新',
    'enableReasoning': '启用推理',
    'disableReasoning': '禁用推理',
    'lightMode': '亮色模式',
    'darkMode': '深色模式',
    'reasoning': '推理',
    'codeReview': '代码审查',
    'pending': '待处理',
    'applied': '已应用',
    'reverted': '已回退',
    'pendingChanges': '待处理变更',
    'appliedChanges': '已应用变更',
    'revertedChanges': '已回退变更',
    'apply': '应用',
    'reject': '拒绝',
    'applyAll': '全部接受',
    'rejectAll': '全部拒绝',
    'autoApproveAll': '全部自动审批（实验性）',
    'autoApproveWarning': '有风险：AI 将自动执行命令并应用文件修改，不再向你逐项确认。',
    'errNoContent': '模型没有返回任何内容。可能它只输出了思考过程，或回复被中断了。请重试、降低思考强度，或在模型设置里调大「最大输出 tokens」。',
    'errTruncated': '模型还没生成完就达到了最大输出 tokens 上限（通常是在思考阶段被截断）。请在模型设置里调大「最大输出 tokens」，或降低思考强度后重试。',
    'revert': '回退',
    'revertFailed': '回退失败',
    'close': '关闭',
    'commandExecution': '命令执行',
    'pendingApproval': '待批准',
    'reviewCommand': '审批',
    'workingDirectory': '工作目录',
    'commandApprovalHint': '请先确认命令和工作目录；执行后的影响可能无法撤销。',
    'commandFailed': '命令执行失败。',
    'changeFailed': '执行失败',
    'from': '从:',
    'to': '到:',
    'source': '源:',
    'destination': '目标:',
    'result': '结果:',
    'execute': '执行',
    'read': '读取',
    'list': '列出',
    'search': '搜索',
    'find': '查找',
    'edit': '编辑',
    'send': '发送',
    'editMessagePlaceholder': '编辑消息...',
    'create': '创建',
    'newFolder': '新建文件夹',
    'rename': '重命名',
    'copy': '复制',
    'run': '运行',
    'openApp': '打开应用',
    'open': '打开',
    'systemInfo': '系统信息',
    'question': '问题',
    'thinking': '思考中',
    'writing': '输出中',
    'toolResult': '工具结果',
    'you': '你',
    'aiAsking': 'AI 正在提问',
    'typeAnswerHint': '在下方输入框输入回答后发送',
    'answered': '已回答',
    'sendHintEnter': 'Enter 发送 · Shift+Enter 换行',
    'sendHintCmd': 'Cmd/Ctrl+Enter 发送',
    'effortFast': '快速',
    'effortAuto': '自动 · 按问题难度选择思考深度',
    'previewAnnotate': '标注位置精准修改',
    'previewAnnotateHint': '点击页面标注坐标 · 自动填入对话',
    'previewAnnotateClear': '清除标注',
    'modePlan': '计划模式',
    'modeTask': '任务模式',
    'modeOrchestrate': '编排模式',
    'modeRsi': 'RSI 模式',
    'modeMenu': '模式与扩展',
    'effortBalanced': '均衡',
    'effortDeep': '深度',
    // Slash commands
    'commandsTitle': '命令',
    'cmdHelp': '显示可用命令',
    'cmdClear': '开始新对话',
    'cmdCompact': '总结并释放上下文',
    'cmdPlan': '切换计划模式（只读规划）',
    'cmdGoal': '开始或替换一个长期目标',
    'cmdMode': '设置智能体模式：standard | goal | orchestrate | rsi',
    'agentModeStandard': '标准',
    'agentModeStandardHint': '默认编码循环 —— 一次请求，端到端完成。',
    'agentModeGoal': '目标模式',
    'agentModeGoalHint': '长期目标推进，直到外部完成条件验证通过。',
    'agentModeOrchestrate': '编排模式',
    'agentModeOrchestrateHint': '主控 + 子智能体：拆解、并行调研、汇总裁决。',
    'agentModeRsi': 'RSI+RL',
    'agentModeRsiHint': 'RL-style search toward the frozen goal: sample, score with an orchestrated judge panel, accept only if reward beats best, stop at plateau.',
    'cmdReview': '只读审查 Git 改动',
    'cmdWorktree': '管理隔离的 Git 工作树',
    'cmdInit': '分析项目并生成 AGENTS.md',
    'cmdAgents': '打开 AGENTS.md 项目记忆',
    'cmdModel': '切换模型',
    'cmdMemory': '查看我记住的关于你的信息',
    'cmdDiff': '总结当前 git 差异',
    'cmdCommit': '暂存改动并提交',
    'helpTitle': 'ConeCode 命令',
    'helpProjectCommands': '项目命令',
    'noAgentsMd': '还没有 AGENTS.md —— 运行 /init 来创建。',
    'goalRunning': '目标执行中',
    'goalPaused': '目标已暂停',
    'pauseGoal': '暂停目标',
    'resumeGoal': '继续目标',
    'editGoal': '编辑目标',
    'clearGoal': '清除目标',
    'goalResumePrompt': '继续执行当前目标。重新检查当前进度，并持续工作到完成条件得到验证。',
    'goalUpdatedPrompt': '当前目标已更新，请把下面内容作为新的完成条件：',
    'reviewReadOnly': '按优先级输出问题 · 只读',
    'reviewUncommitted': '审查未提交改动',
    'reviewUncommittedHint': '包含当前工作区的已暂存、未暂存和未跟踪路径。',
    'reviewBase': '与基准分支对比审查',
    'reviewBaseHint': '审查从合并基点到 HEAD 的分支差异。',
    'reviewCommit': '审查指定提交',
    'reviewCommitHint': '通过 SHA、标签或修订名准确审查一个提交。',
    'reviewCommitPlaceholder': '提交 SHA 或修订名',
    'reviewNeedsRepo': '请先打开 Git 仓库中的项目。',
    'reviewReadFailed': '无法读取所选 Git 改动。',
    'reviewNoChanges': '这个审查范围内没有改动。',
    'reviewPreparing': '正在准备审查…',
    'startReview': '开始只读审查',
    'worktrees': '工作树',
    'worktreesHint': '在隔离的 Git 检出中并行处理任务。',
    'worktreeName': '任务名称（可选）',
    'createWorktree': '创建隔离工作树',
    'worktreeNeedsRepo': '请先打开一个 Git 仓库。',
    'worktreeLoadFailed': '无法加载 Git 工作树。',
    'worktreeCreateFailed': '无法创建工作树。',
    'worktreeOpenFailed': '无法打开工作树文件夹。',
    'worktreeRemoveFailed': '无法移除工作树。',
    'detachedHead': '游离 HEAD',
    'current': '当前',
    'localCheckout': '主检出目录',
    'uncommitted': '项未提交',
    'removeWorktreeConfirm': '移除这个干净的受管工作树？',
    'compacting': '正在压缩…',
    'contextCompacted': '上下文已压缩',
    'compactFailed': '无法压缩对话。',
    'compact': '压缩',
    'showCompacted': '显示已压缩的消息',
    'hideCompacted': '收起已压缩的消息',
    // Plan mode
    'planMode': '计划模式',
    'plan': '计划',
    'planModeHint': '只读模式 —— AI 会先调研并提出方案，再进行修改。',
    'presentPlan': '方案已就绪',
    'approvePlan': '批准并执行',
    'keepPlanning': '继续规划',
    'planApproved': '方案已批准 —— 现在开始实现。',
    'planBlocked': '计划模式（只读）下已拦截。请改为提出方案。',
    // To-dos
    'todos': '待办',
    'todoUpdated': '待办列表已更新。',
    'deleteTodo': '删除此项',
    'clearTodos': '清空待办',
    'expandTodos': '展开完整待办',
    'collapseTodos': '收起完整待办',
    'allTodosCompleted': '待办已全部完成',
    // Rollback
    'undoChange': '撤销改动',
    'undoChangeConfirmTitle': '只撤销这个工作区改动？',
    'undoChangeKeepsChat': '对话会保留，AI 会收到工作区状态已改变的通知。',
    'rollbackConversation': '回滚对话',
    'checkpointRollbackTitle': '回滚到这个对话检查点？',
    'checkpointRollbackChat': '这条消息及之后的对话会被删除，可撤销的文件改动将恢复。',
    'checkpointExternalEffects': '已执行的命令和电脑操作仍然生效，并保持“已应用”状态。',
    'confirmCheckpointRollback': '确认回滚检查点',
    'checkpointUnavailable': '此改动没有可用的对话检查点。',
    // Approval modes
    'approvalMode': '审批',
    'approvalSuggest': '逐项确认',
    'approvalAutoEdit': '自动编辑',
    'approvalFullAuto': '全自动',
    'approvalSuggestDesc': '每次编辑和命令都先询问（最安全）。',
    'approvalAutoEditDesc': '自动应用文件编辑；运行命令前询问。',
    'approvalFullAutoDesc': '自动应用编辑并运行命令，不再询问（有风险）。',
    // Tool-call protocol
    'toolCallMode': '工具调用',
    'toolModeAuto': '自动',
    'toolModeNative': '原生',
    'toolModePrompt': '提示词',
    'toolModeAutoDesc': '模型支持时使用服务商的原生函数调用（推荐）。',
    'toolModeNativeDesc': '始终发送工具定义 —— 适用于支持工具但未在模型列表中声明的接口。',
    'toolModePromptDesc': '不发送工具定义，改用提示词中的 ```json 动作格式。',
    'callingTool': '调用',
    // Command sandbox
    'sandbox': '命令沙箱',
    'sandboxOn': '受限运行',
    'sandboxOff': '不受限制',
    'sandboxOnDesc': '命令可以读取你的电脑，但只能写入工作区和临时目录。推荐。',
    'sandboxOffDesc': '命令以你的完整权限运行，可以修改这台电脑上的任何文件。',
    'sandboxNetwork': '允许访问网络（安装依赖需要）',
    'sandboxUnavailable': '命令沙箱目前仅支持 macOS，在此系统上命令不受限制。',
    'notifications': '通知',
    'notificationsDesc': '任务完成或需要你处理时发送系统通知。',
    'notification_never': '从不',
    'notification_background': '仅后台',
    'notification_always': '始终',
    'notifyApprovals': '操作需要批准时通知我',
    'preventSleepWhileRunning': '任务运行时防止应用挂起',
    'taskReadyTitle': '任务已就绪',
    'taskReadyBody': 'ConeCode 已完成当前轮次。',
    'approvalReadyTitle': '需要批准',
    'approvalReadyBody': 'ConeCode 正在等待你审查一个操作。',
    // Memory
    'memory': '记忆',
    'memoryEnabled': '开启',
    'memoryHint': 'ConeCode 记住的东西：你希望怎么推进工作、这个项目有哪些既定事实、以及你习惯的沟通方式。会自动应用到每个新对话。',
    'memoryEmpty': '还没有学到任何东西。使用过程中会自动积累。',
    'memoryAdd': '添加',
    'memoryAddPlaceholder': '直接教它，例如「始终用中文回答」',
    'memoryForget': '忘掉这条',
    'memoryClear': '清空全部记忆',
    'memoryClearConfirm': '删除所有记忆？',
    'memoryProjectOnly': '仅本项目',
    'memoryStyle': '沟通习惯',
    'memoryWorkflow': '工作方式',
    'cmdAddDir': '再打开一个文件夹',
    'addFolder': '添加文件夹',
    'removeFolder': '关闭此文件夹',
    'addedFolder': '已添加文件夹',
    'addFolder_duplicate': '该文件夹已经打开了。',
    'addFolder_inside-existing': '该文件夹已包含在已打开的目录里。',
    'addFolder_contains-existing': '该文件夹包含了已打开的目录 —— 请先关闭它们。',
    'captureWhere': '记住这条 —— 放在哪里？',
    'captureProject': '仅本项目',
    'captureUser': '所有项目',
    'memoryFilesTitle': '生效中的记忆文件',
    'memoryScope_user': '你的，适用所有项目',
    'memoryScope_ancestor': '继承自上层目录',
    'memoryScope_project': '本项目',
    'memoryNoFiles': '还没有记忆文件 —— 用「# 你的规则」新建一条。',
    'memoryOpenHint': '用 /memory project 或 /memory user 打开。以「# 」开头发消息即可记录新规则。',
    'memoryNoSuchFile': '没有匹配的记忆文件。',
    'memoryProject': '关于本项目',
    'memoryLearned': '依据',
    'memoryAddProjectPlaceholder': '关于这个代码库的事实，例如「纯逻辑放在 src/core」',
    'memoryProjectNeedsFolder': '请先打开一个文件夹 —— 项目记忆需要有归属的项目。',
    'memoryCodeIssue': '常见代码问题',
    'memoryFact': '事实',
    'memoryTitle': '我记住的关于你的信息',
    'memoryNone': '我还没有记住关于你的任何信息。',
    // @ mentions
    'mentionFiles': '附加文件',
    // Git
    'gitBranch': '分支',
    'gitClean': '干净',
    // Web + MCP + sub-agents
    'fetchWeb': '抓取网页',
    'searchWeb': '联网搜索',
    'downloadFile': '下载',
    'subAgent': '子代理',
    'mcpTool': 'MCP 工具',
    'mcpServers': 'MCP 服务器',
    // Skills (plugin library)
    'skills': '技能',
    'skillsHint': '可复用的专业能力，AI 遇到相关任务时会自动加载。可只部署到本项目，也可对所有项目生效。',
    'skillLibrary': '插件库',
    'skillDeploy': '部署',
    'skillProjectShort': '本项目',
    'skillDeployGlobal': '对所有项目生效',
    'skillDeployProject': '只部署到当前项目',
    'skillNeedsProject': '请先打开一个项目，再部署到该项目。',
    'skillRemove': '移除',
    'skillEnable': '启用',
    'skillDisable': '停用',
    'skillDisabled': '已停用',
    'skillShadowedBadge': '已覆盖',
    'skillShadowedTip': '同 ID 的项目技能会覆盖这个全局技能。',
    'skillOpen': '打开 SKILL.md',
    'skillGlobal': '所有项目可用',
    'skillProject': '仅当前项目',
    'useSkill': '技能',
    // Custom skills
    'skillNew': '新建技能',
    'skillEdit': '编辑',
    'skillImport': '导入文件',
    'skillImportError': '该文件不是可用的 SKILL.md。',
    'skillCustomBadge': '自定义',
    'skillCustomTip': '这是你自己写的或导入的。ConeCode 不会审核自定义技能。',
    'skillGlobalShort': '所有项目',
    'skillExists': '该范围下已存在同名技能。',
    'skillNamePlaceholder': '名称，例如：本项目代码规范',
    'skillDescPlaceholder': 'AI 在什么情况下该用它？',
    'skillDescHint': '在 AI 决定加载之前，它只能看到这一行 —— 请写清楚何时使用。',
    'skillBodyPlaceholder': '具体指令，Markdown 格式。明确该做什么、不该做什么。',
    'skillNameError': '名称必填。',
    'skillDescError': '描述必填（最多 200 字符）。',
    'skillBodyError': '请写出真正的指令内容（至少一句话）。',
    'skillRiskTitle': '自定义技能由你自己负责',
    'skillRiskBody': '技能就是 AI 会遵照执行的指令，它可以让 AI 修改文件、执行命令、访问网络。ConeCode 不会审核技能内容，也不会对其做任何限制。请只添加你自己写的或完全信任的技能 —— 你在这里添加的内容以及由此产生的一切后果，均由你自己承担。',
    'skillRiskStillApplies': '你的审批模式和命令沙箱依然对技能实际执行的操作生效。',
    'skillRiskAccept': '我已了解风险，后果自负',
    'gitStatus': 'Git 状态',
    'gitDiff': 'Git 差异',
    'thinkingTime': '思考时间',
    // Terminal
    'terminal': '终端',
    'terminals': '终端',
    'newTerminal': '新建终端',
    'renameTerminal': '重命名终端',
    // Live preview (built-in browser)
    'preview': '预览',
    'previewStart': '启动预览',
    'previewStop': '停止',
    'previewRestart': '重启',
    'previewStarting': '正在启动…',
    'previewRunning': '运行中',
    'previewIdle': '未运行',
    'previewFailed': '预览启动失败',
    'previewBack': '后退',
    'previewForward': '前进',
    'previewStopLoading': '停止加载',
    'previewOpenExternal': '在浏览器中打开',
    'previewDesktop': '桌面',
    'previewTablet': '平板',
    'previewMobile': '手机',
    'previewLogs': '输出',
    'previewClearLogs': '清空输出',
    'previewNoOutput': '暂无输出',
    'previewNoFolder': '还没有打开项目',
    'previewNoFolderHint': '打开一个文件夹，我就能把它运行起来，并直接显示在这里。',
    'previewNotDetectedHint': '没有检测到开发脚本或 index.html。请输入启动命令，或直接填写端口号。',
    'previewCustomCommand': '自定义启动命令',
    'previewAddressPlaceholder': '输入网址',
    'previewNewTab': '新标签页',
    'previewOpen': '打开',
    'previewStaticFiles': '静态文件',
    'previewCommandPlaceholder': '启动这个项目的命令',
    'previewOrTypeUrl': '也可以在上方地址栏输入任意网址',
    'previewPick': '选取页面元素',
    'previewPickHint': '点击页面上的元素，把它发给 AI · 按 Esc 取消',
    'previewPickedElement': '关于这个元素：',
    'previewRetry': '重试',
    'previewExited': '预览进程已退出',
    'unsaved': '未保存',
    // Computer control (the agent drives the real screen)
    'computerControl': '电脑操控',
    'computerActive': 'AI 可以使用你的鼠标和键盘',
    'computerInactive': '已关闭 —— AI 无法操作屏幕',
    'computerUnsupported': '电脑操控目前仅支持 macOS 和 Windows。',
    'computerWarnTitle': '这会把机器交出去',
    'computerWarnBody': '打开后，AI 能看到你的屏幕，并在任意位置点击和输入 —— 包括 ConeCode 以外的应用。用完请及时关闭。',
    'computerEnable': '允许 AI 操控这台电脑',
    'computerDisable': 'AI 正在操控这台电脑',
    'computerSessionOnly': '仅本次会话有效 —— 每次启动都是关闭状态',
    'computerStopNow': '立即停止并收回控制权',
    'computerPermissions': 'macOS 权限',
    'computerAccessibility': '辅助功能',
    'computerAccessibilityHint': '移动指针和输入都需要它。没有授权时，macOS 会静默丢弃这些事件。',
    'computerScreenRecording': '屏幕录制',
    'computerScreenRecordingHint': '截屏需要它。请在“系统设置 › 隐私与安全性”中授权。',
    'computerGranted': '已授权',
    'computerOpenSettings': '打开设置',
    'computerRestartHint': 'macOS 需要重启应用后，新授予的权限才会生效。',
    'computerApproval': '审批方式',
    'computerApprovalAsk': '每次点击和按键都会先请你确认。想让它连续执行，请把审批模式切到“全自动”。',
    'computerApprovalAuto': '当前是“全自动”审批，操作会直接执行，不再询问。请留意下面的记录。',
    'computerScreen': '屏幕',
    'computerAsSeen': '（模型看到的尺寸）',
    'computerLastShot': 'AI 最近看到的画面',
    'computerActivity': '操作记录',
    'computerNoActivity': '暂无操作',
    // Model auto-detect
    'detectModels': '检测模型',
    'detecting': '检测中…',
    'modelsFound': '个模型',
    'detectFailed': '检测失败',
    'detectHint': '填入 Base URL 与 API Key，自动识别可用模型及其上下文长度。',
    // Changed files panel
    'panels': '面板',
    'panelsMore': '更多工具',
    'openFile': '打开文件…',
    'changedFiles': '修改的文件',
    'filesChanged': '个文件已更改',
    'noChanges': '暂无更改',
    // Remote control (phone)
    'remoteControl': '远程控制',
    'remoteDesc': '通过 Wi-Fi 或公网，用手机远程操控 ConeCode。',
    'scanToConnect': '扫码连接',
    'lanAddress': '同一 Wi-Fi 下',
    'publicLink': '公网链接（内网穿透）',
    'startServer': '开启',
    'stopServer': '停止',
    'serverOnline': '已开启',
    'serverOff': '未开启',
    'serverStarting': '启动中…',
    'tunnelStarting': '正在建立隧道…',
    'tunnelHint': '已内置 cloudflared，通常无需任何安装；若多次失败请检查网络，或改用 ngrok（需注册账号并配置 authtoken）。',
    'devicesConnected': '台已连接',
    'remotePassword': '连接密码',
    'remotePasswordPlaceholder': '可选，留空则不设密码',
    'remotePasswordHint': '设置后，密码会写入二维码，扫码即可自动连接；请勿外泄二维码。',
    'tunnelMethod': '公网方式',
    'tunnelCloudflare': 'Cloudflare（内置，免账号）',
    'tunnelCustom': '自定义命令',
    'auto': '自动（就近）',
    'tunnelCustomHint': '用 {url} 或 {port} 作占位符；命令需打印出公网 https:// 地址。',
    'remotePasswordReq': '至少 6 位，且包含大写字母、数字和符号。',
    'remotePublicNeedsPassword': '公网模式必须先在上方设置密码。',
    'tunnelNotInstalled': '未找到该隧道程序。Cloudflare 已内置；ngrok 需自行安装（如 brew install ngrok）并填入 authtoken。',
    'tunnelTimeout': '建立隧道超时，可能被网络拦截。请重试或更换公网方式。',
    'tunnelFailed': '隧道启动失败，详情见下方输出（及 ~/.conecode-tunnel.log）。',
    'ngrokHint': '在 ngrok.com 注册获取 authtoken。没装 ngrok？用下面的一键安装。',
    'ngrokInstall': '一键安装 ngrok',
    'cfdAdaptiveHint': '自动下载适配本机的 cloudflared（macOS / Windows）。',
    'cfdInstall': '一键安装 cloudflared',
    'cfdInstalling': '正在安装 cloudflared…',
    'cfdInstalled': 'cloudflared 安装完成。可打开公网链接。',
    'cfdInstallFailed': 'cloudflared 安装失败',
    'ngrokInstalling': '正在安装 ngrok…',
    'ngrokInstalled': 'ngrok 安装完成。填入 authtoken 后即可开公网链接。',
    'ngrokInstallFailed': 'ngrok 安装失败',
    'connectedDevices': '已连接设备',
    'kickDevice': '踢出',
    'noDevices': '暂无设备连接。',
    'copyLink': '复制链接',
    'copied': '已复制',
  },
  ja: {
    "briefTitle": "アイデアからソフトウェアを作る",
    "briefDescription": "作りたいものを説明すると、AI が要件を整理して開発用プロンプトを作成します。",
    "briefIdeaLabel": "ソフトウェアのアイデア",
    "briefPlaceholder": "何を、誰のために作りますか？必要な機能、対応環境、デザインの希望も書いてください。",
    "briefInputHint": "Enter で生成 · Shift+Enter で改行",
    "briefGenerate": "要件を整理して生成",
    "briefRegenerate": "再生成",
    "briefThinking": "要件、例外処理、受け入れ基準を整理しています…",
    "briefOutputTitle": "開発プロンプト · 編集可能",
    "briefFolderHint": "開始時に ~/ConeCode Projects/ 内に新しいフォルダーを作成します。",
    "briefOutputHint": "Enter で開始 · Shift+Enter で改行",
    "briefCopy": "コピー",
    "briefCopied": "コピー済み",
    "briefStart": "開発を開始",
    "briefStarting": "開始中…",
    "briefGenerateFailed": "完全なプロンプトを生成できませんでした。モデルの接続を確認して再試行してください。",
    "briefFolderFailed": "プロジェクトフォルダーを作成または開けませんでした。権限を確認してください。",
    "briefConversationChanged": "準備中に会話が切り替わったため開始を中止しました。ここに戻って再試行してください。",
    "briefStartFailed": "開始できませんでした。プロンプトはコピーまたは再試行できます。",
    "briefCopyFailed": "コピーできませんでした。プロンプトを選択して手動でコピーしてください。",
    'newChat': '新しいチャット',
    'sidebarNoProject': 'プロジェクトなし',
    'sidebarFiles': 'ファイル',
    'installHolding': 'インストール中 — モデル一時停止、完了後に自動再開',
    'installContinue': 'インストール完了。モデルを再開して作業を続けます。',
    'settings': '設定',
    'language': '言語',
    'typeMessage': 'メッセージを入力...',
    // Agent home
    'homeGreetingMorning': 'おはようございます。今日は何をしますか？',
    'homeGreetingAfternoon': 'こんにちは。次は何をしますか？',
    'homeGreetingEvening': 'こんばんは。今夜は何をしますか？',
    'homeGreetingNight': 'まだ起きていますか？何をしますか？',
    'homeClean': 'クリーン',
    'homeFiles': 'ファイル',
    'homeScripts': 'スクリプト',
    'homeRescan': 'プロジェクトを再読み込み',
    'homeNoFolder': 'フォルダが開かれていません',
    'homeUncommitted': '件未コミット',
    'homeNoTests': 'テストなし',
    'homeFindWork': '見つけた作業',
    'homeFindWorkAction': '作業を探す',
    'homeRefindWork': '再検索',
    'homeFindFailed': '何をすべきか判断できませんでした',
    'homeIdleTitle': 'プロジェクトを見てみます',
    'homeIdleBody': 'git の状態・TODO コメント・テスト・スクリプトを読んで、すぐ始められる具体的なタスクを提案します。',
    'homeOpenFolderTitle': 'まずプロジェクトを開いてください',
    'homeOpenFolderBody': 'フォルダを開けば状態を読んで次にすべきことを提案できます —— 新規プロジェクトの作成も可能です。',
    'homeResume': '前回の続きから',
    'homeContinue': '続ける',
    'homeOpenOnly': '開くだけ',
    'homeOpenTodos': '件未完了',
    'homeStartNew': '新しく始める',
    // The recommended next action
    'recLabel': '次はこれ',
    'recResume': 'やりかけを終わらせましょう —— 残り',
    'recReview': '未コミットの変更をレビュー —— 変更ファイル数：',
    'recTask': '見つけた最優先タスクから：',
    'recTests': 'テストがありません —— まず一つ追加',
    'recTestsPrompt': 'このプロジェクトにはテストがありません。最も重要な振る舞いを選び、テストランナーが無ければ用意し、意味のあるテストを一つ書いてください。実行して通ることを見せてください。',
    'recStart': 'プロジェクトを開くか、下から選んでください',
    'recStartNew': 'すべてクリーンです —— 新しく何か作りましょう',
    'recDialogInputAria': '次のアクション入力',
    'recDialogPlaceholder': '提案の指示を編集するか、自分で書いてください。Enter で開始。',
    'recDialogStartPlaceholder': '作りたいものを書くか、空欄のまま下から選んでください…',
    'recDialogHint': 'Enter で開始 · Shift+Enter で改行',
    'recDialogSend': '開始',
    'recDialogBrowseIdeas': 'アイデアを見る',
    // Autopilot
    'autopilotTitle': '選ぶだけ、あとは私が作ります',
    'autopilotSubtitle': 'フォルダ作成・実装・動作確認まで自動',
    'autopilotThinking': 'アイデアを考え中…',
    'autopilotFrom': '提案元：',
    'autopilotMore': '別の案',
    'autopilotMedium': 'やや大きめ',
    'autopilotCreating': 'プロジェクトフォルダを作成中',
    'autopilotBuilding': '開発中',
    'autopilotVerifying': '実際に実行して確認中',
    'autopilotRepairing': '失敗箇所を修正中',
    'autopilotRepairingHint': 'まだ通っていません。修正して再実行します。試行',
    'autopilotDone': '完成・動作確認済み',
    'autopilotDoneHint': 'プロジェクトを作成し、テストが実際に通りました。',
    'autopilotOpenReadme': 'README を開く',
    'autopilotFailed': '完了できませんでした',
    'autopilotFailedHint': '数回試しても通りませんでした。経緯はすべて会話に残っています。次の指示をどうぞ。',
    'autopilotNoVerify': '検証用のコマンドが報告されませんでした。',
    'autopilotNoFolder': 'プロジェクトフォルダを作成できませんでした。',
    'homeNewProject': '新規プロジェクト',
    'homeNewProjectDesc': 'アイデアを伝えれば、動くコードとテストまで用意します。',
    'homeNewProjectHint': '作りたいものを説明してください。技術選定・雛形作成・動作確認まで行います。',
    'homeNewProjectPlaceholder': '例：フォルダを監視して新しい画像を圧縮する CLI',
    'homeNewProjectNeedsDir': '置き場所を確認します。',
    'homeCreate': '作成する',
    'homeOpenFolderDesc': '既存のコードで作業する。',
    'homeExplore': 'このコードベースを把握',
    'homeExploreDesc': '構成と全体像を素早く理解する。',
    'homeExplorePrompt': 'このコードベースを案内してください：何をするもので、どう構成され、エントリーポイントはどこか、そして編集前に知るべき三つのこと。正確さのため実際のファイルを十分に読んでください。',
    'homeReview': '変更をレビュー',
    'homeReviewDesc': '未コミットのコードを点検する。',
    'homeReviewPrompt': 'git status と git diff で未コミットの変更をレビューしてください。実際の欠陥・エッジケース・周囲のコードとの不整合を探し、最初に直すべきものを教えてください。まだコードは変更しないでください。',
    'justNow': 'たった今',
    'minutesAgoShort': '分前',
    'hoursAgoShort': '時間前',
    'daysAgoShort': '日前',
    'taskKind_bug': 'バグ',
    'taskKind_feature': '機能',
    'taskKind_refactor': 'リファクタ',
    'taskKind_test': 'テスト',
    'taskKind_docs': 'ドキュメント',
    'taskKind_chore': '雑務',
    'taskEffort_quick': 'すぐ',
    'taskEffort_medium': '中',
    'taskEffort_large': '大',
    'taskRisk_low': '低リスク',
    'taskRisk_medium': 'やや注意',
    'taskRisk_high': '高リスク',
    'selectModelHint': 'モデルを選択してメッセージを入力',
    'dismiss': '閉じる',
    'ai': 'AI',
    'searchModels': 'モデルを検索...',
    'selectModel': 'モデルを選択',
    'noModels': 'モデルが見つかりません',
    'favorites': 'お気に入り',
    'recent': '最近使用',
    'textChat': 'テキストチャット',
    'vision': 'ビジョン',
    'imageGen': '画像生成',
    'audioIn': '音声入力',
    'audioOut': '音声出力',
    'functions': '関数呼び出し',
    'context': 'コンテキスト',
    'maxOutput': '最大出力',
    'contextWindow': 'コンテキスト長',
    'editLimits': '上限を編集',
    'readFromApi': 'APIから取得',
    'reset': 'リセット',
    'contextUsage': 'コンテキスト使用量',
    'contextLeft': '残りコンテキスト',
    'used': '使用済み',
    'remaining': '残り',
    'compactions': '圧縮回数',
    'tokens': 'トークン',
    'messages': 'メッセージ',
    'attachedFiles': '添付ファイル',
    'systemPrompt': 'システムプロンプト',
    'estimated': '推定値',
    'attachFiles': 'ファイルを添付',
    'providerSettings': 'プロバイダー設定',
    'setGeneral': '一般',
    'setGeneralDesc': 'AI がどこまで自分で行えるか、どう制限されるか。',
    'setProviders': 'プロバイダー',
    'setProvidersDesc': 'API の URL とキー。入力後にモデルを自動検出できます。',
    'setMcpDesc': 'MCP サーバーを接続して追加のツールを提供します。',
    'addProvider': 'プロバイダー追加',
    'enabled': '有効',
    'disabled': '無効',
    'cancel': 'キャンセル',
    'save': '保存',
    'cannotPreview': 'このファイルはプレビューできません',
    'delete': '削除',
    'providerName': 'プロバイダー名',
    'baseUrl': 'ベース URL',
    'apiKey': 'APIキー',
    'defaultModel': 'デフォルトモデル',
    'timeout': 'タイムアウト (ms)',
    'default': 'デフォルト',
    'none': 'なし',
    'custom': 'カスタム',
    'openFolder': 'フォルダを開く',
    'closeFolder': 'フォルダを閉じる',
    'closeFile': 'ファイルを閉じる',
    'refresh': '更新',
    'enableReasoning': '推論を有効にする',
    'disableReasoning': '推論を無効にする',
    'lightMode': 'ライトモード',
    'darkMode': 'ダークモード',
    'reasoning': '推論',
    'codeReview': 'コードレビュー',
    'pending': '保留中',
    'applied': '適用済み',
    'reverted': '元に戻しました',
    'pendingChanges': '保留中の変更',
    'appliedChanges': '適用済みの変更',
    'revertedChanges': '元に戻した変更',
    'apply': '適用',
    'reject': '拒否',
    'applyAll': 'すべて適用',
    'rejectAll': 'すべて拒否',
    'autoApproveAll': 'すべて自動承認（実験的）',
    'autoApproveWarning': 'リスクあり：AI が確認なしでコマンドを実行し、ファイルの変更を自動的に適用します。',
    'errNoContent': 'モデルが内容を返しませんでした。推論だけで終わったか、応答が途中で打ち切られた可能性があります。再試行するか、思考強度を下げるか、最大出力トークン数を増やしてください。',
    'errTruncated': 'モデルが完了する前に最大出力トークン数に達しました（多くは推論の途中で打ち切り）。最大出力トークン数を増やすか、思考強度を下げて再試行してください。',
    'revert': '元に戻す',
    'revertFailed': '元に戻せませんでした',
    'close': '閉じる',
    'commandExecution': 'コマンド実行',
    'pendingApproval': '承認待ち',
    'reviewCommand': '確認',
    'workingDirectory': '作業ディレクトリ',
    'commandApprovalHint': '実行前にコマンドと作業ディレクトリを確認してください。影響を元に戻せない場合があります。',
    'commandFailed': 'コマンドの実行に失敗しました。',
    'changeFailed': '失敗',
    'from': 'から:',
    'to': 'へ:',
    'source': 'ソース:',
    'destination': '宛先:',
    'result': '結果:',
    'execute': '実行',
    'read': '読み取り',
    'list': '一覧',
    'search': '検索',
    'find': '検索',
    'edit': '編集',
    'send': '送信',
    'editMessagePlaceholder': 'メッセージを編集...',
    'create': '作成',
    'newFolder': '新しいフォルダ',
    'rename': '名前変更',
    'copy': 'コピー',
    'run': '実行',
    'openApp': 'アプリを開く',
    'open': '開く',
    'systemInfo': 'システム情報',
    'question': '質問',
    'thinking': '思考中',
    'writing': '出力中',
    'toolResult': 'ツール結果',
    'you': 'あなた',
    'aiAsking': 'AI が質問しています',
    'typeAnswerHint': '下の入力欄に回答を入力して送信してください',
    'answered': '回答済み',
    'sendHintEnter': 'Enter で送信 · Shift+Enter で改行',
    'sendHintCmd': 'Cmd/Ctrl+Enter で送信',
    'effortFast': '高速',
    'effortAuto': '自動 · 質問に合わせて思考の深さを選択',
    'previewAnnotate': '位置をピン留めして精密編集',
    'previewAnnotateHint': 'ページをクリックして座標をピン · チャットに自動入力',
    'previewAnnotateClear': 'ピンをクリア',
    'modePlan': 'プランモード',
    'modeTask': 'タスクモード',
    'modeOrchestrate': 'オーケストレーション',
    'modeRsi': 'RSI モード',
    'modeMenu': 'モードと拡張',
    'effortBalanced': 'バランス',
    'effortDeep': '深い思考',
    // Slash commands
    'commandsTitle': 'コマンド',
    'cmdHelp': '使用可能なコマンドを表示',
    'cmdClear': '新しいチャットを開始',
    'cmdCompact': '要約してコンテキストを解放',
    'cmdPlan': 'プランモードの切り替え（読み取り専用）',
    'cmdGoal': '長期目標を開始または置き換え',
    'cmdMode': 'エージェントモードを設定: standard | goal | orchestrate | rsi',
    'agentModeStandard': '標準',
    'agentModeStandardHint': '既定のコーディングループ —— 1 リクエストを最後まで。',
    'agentModeGoal': '目標モード',
    'agentModeGoalHint': '外部の完了条件が検証されるまで長期目標を継続。',
    'agentModeOrchestrate': 'オーケストレーション',
    'agentModeOrchestrateHint': '指揮 + サブエージェント：分解・並列調査・統合。',
    'agentModeRsi': 'RSI+RL',
    'agentModeRsiHint': '固定目標への RL 的探索。候補を生成し、編成した審査エージェントで採点。報酬が最良を超えた時のみ採用し、高原で停止。',
    'cmdReview': 'Git の変更を読み取り専用でレビュー',
    'cmdWorktree': '分離された Git worktree を管理',
    'cmdInit': 'プロジェクトを分析して AGENTS.md を作成',
    'cmdAgents': 'AGENTS.md プロジェクトメモリを開く',
    'cmdModel': 'モデルを切り替え',
    'cmdMemory': '覚えていることを表示',
    'cmdDiff': '現在の git 差分を要約',
    'cmdCommit': '変更をステージしてコミット',
    'helpTitle': 'ConeCode コマンド',
    'helpProjectCommands': 'プロジェクトコマンド',
    'noAgentsMd': 'AGENTS.md がまだありません —— /init で作成してください。',
    'goalRunning': '目標を実行中',
    'goalPaused': '目標を一時停止中',
    'pauseGoal': '目標を一時停止',
    'resumeGoal': '目標を再開',
    'editGoal': '目標を編集',
    'clearGoal': '目標をクリア',
    'goalResumePrompt': '現在の目標を再開してください。進捗を再確認し、完了条件を検証できるまで続けてください。',
    'goalUpdatedPrompt': '現在の目標を更新しました。次の内容を新しい完了条件として使用してください：',
    'reviewReadOnly': '優先度付きの指摘 · 読み取り専用',
    'reviewUncommitted': '未コミット変更をレビュー',
    'reviewUncommittedHint': '現在のチェックアウトのステージ済み、未ステージ、未追跡パスを含みます。',
    'reviewBase': 'ベースブランチとの差分をレビュー',
    'reviewBaseHint': 'マージベースから HEAD までのブランチ差分をレビューします。',
    'reviewCommit': 'コミットをレビュー',
    'reviewCommitHint': 'SHA、タグ、またはリビジョンで一つのコミットをレビューします。',
    'reviewCommitPlaceholder': 'コミット SHA またはリビジョン',
    'reviewNeedsRepo': 'Git リポジトリ内のプロジェクトを開いてください。',
    'reviewReadFailed': '選択した Git 変更を読み取れませんでした。',
    'reviewNoChanges': 'このレビュー範囲には変更がありません。',
    'reviewPreparing': 'レビューを準備中…',
    'startReview': '読み取り専用レビューを開始',
    'worktrees': 'Worktree',
    'worktreesHint': '分離された Git チェックアウトでタスクを並行実行します。',
    'worktreeName': 'タスク名（任意）',
    'createWorktree': '分離 worktree を作成',
    'worktreeNeedsRepo': 'Git リポジトリを開いてください。',
    'worktreeLoadFailed': 'Git worktree を読み込めませんでした。',
    'worktreeCreateFailed': 'worktree を作成できませんでした。',
    'worktreeOpenFailed': 'worktree フォルダを開けませんでした。',
    'worktreeRemoveFailed': 'worktree を削除できませんでした。',
    'detachedHead': 'Detached HEAD',
    'current': '現在',
    'localCheckout': 'メインチェックアウト',
    'uncommitted': '件未コミット',
    'removeWorktreeConfirm': 'このクリーンな管理 worktree を削除しますか？',
    'compacting': '圧縮中…',
    'contextCompacted': 'コンテキストを圧縮しました',
    'compactFailed': '会話を圧縮できませんでした。',
    'compact': '圧縮',
    'showCompacted': '圧縮したメッセージを表示',
    'hideCompacted': '圧縮したメッセージを隠す',
    // Plan mode
    'planMode': 'プランモード',
    'plan': 'プラン',
    'planModeHint': '読み取り専用 —— AI はまず調査して計画を提案してから編集します。',
    'presentPlan': '計画ができました',
    'approvePlan': '承認して実行',
    'keepPlanning': '計画を続ける',
    'planApproved': '計画が承認されました —— 実装を開始します。',
    'planBlocked': 'プランモード（読み取り専用）でブロックされました。計画を提示してください。',
    // To-dos
    'todos': 'ToDo',
    'todoUpdated': 'ToDo リストを更新しました。',
    'deleteTodo': 'この項目を削除',
    'clearTodos': 'リストをクリア',
    'expandTodos': 'ToDo リストを展開',
    'collapseTodos': 'ToDo リストを折りたたむ',
    'allTodosCompleted': 'すべて完了しました',
    // Rollback
    'undoChange': '変更を元に戻す',
    'undoChangeConfirmTitle': 'このワークスペース変更だけを元に戻しますか？',
    'undoChangeKeepsChat': '会話は残り、ワークスペースの変更が AI に通知されます。',
    'rollbackConversation': '会話をロールバック',
    'checkpointRollbackTitle': 'この会話チェックポイントまで戻しますか？',
    'checkpointRollbackChat': 'このメッセージ以降を削除し、元に戻せるファイル変更を復元します。',
    'checkpointExternalEffects': '実行済みのコマンドとパソコン操作は有効なまま、適用済みとして保持されます。',
    'confirmCheckpointRollback': 'チェックポイントへ戻す',
    'checkpointUnavailable': 'この変更には会話チェックポイントがありません。',
    // Approval modes
    'approvalMode': '承認',
    'approvalSuggest': '都度確認',
    'approvalAutoEdit': '自動編集',
    'approvalFullAuto': '全自動',
    'approvalSuggestDesc': '編集とコマンドの前に毎回確認（最も安全）。',
    'approvalAutoEditDesc': 'ファイル編集を自動適用；コマンド実行前に確認。',
    'approvalFullAutoDesc': '編集を自動適用しコマンドも確認なしで実行（リスクあり）。',
    // Tool-call protocol
    'toolCallMode': 'ツール呼び出し',
    'toolModeAuto': '自動',
    'toolModeNative': 'ネイティブ',
    'toolModePrompt': 'プロンプト',
    'toolModeAutoDesc': 'モデルが対応していればプロバイダーの関数呼び出しを使用（推奨）。',
    'toolModeNativeDesc': '常にツール定義を送信 —— 対応しているが公表していないエンドポイント向け。',
    'toolModePromptDesc': 'ツール定義を送らず、プロンプト内の ```json 形式を使用。',
    'callingTool': '呼び出し中',
    // Command sandbox
    'sandbox': 'コマンドサンドボックス',
    'sandboxOn': '制限あり',
    'sandboxOff': '制限なし',
    'sandboxOnDesc': 'コマンドは読み取りは自由ですが、書き込みはワークスペースと一時領域のみ。推奨。',
    'sandboxOffDesc': 'コマンドはあなたの全権限で実行され、このマシンの何でも変更できます。',
    'sandboxNetwork': 'ネットワークアクセスを許可（インストールに必要）',
    'sandboxUnavailable': 'コマンドサンドボックスは macOS のみ対応です。ここでは制限なしで実行されます。',
    'notifications': '通知',
    'notificationsDesc': 'タスクの完了や確認が必要なときに OS 通知を送ります。',
    'notification_never': 'しない',
    'notification_background': 'バックグラウンドのみ',
    'notification_always': '常に',
    'notifyApprovals': '操作の承認が必要なときに通知',
    'preventSleepWhileRunning': 'タスク実行中はアプリの停止を防ぐ',
    'taskReadyTitle': 'タスク完了',
    'taskReadyBody': 'ConeCode が現在のターンを完了しました。',
    'approvalReadyTitle': '承認が必要です',
    'approvalReadyBody': 'ConeCode が操作の確認を待っています。',
    // Memory
    'memory': 'メモリ',
    'memoryEnabled': '有効',
    'memoryHint': 'ConeCode があなたについて学んだこと —— 繰り返し起きるコードの問題と、好みの話し方。新しい会話に自動的に適用されます。',
    'memoryEmpty': 'まだ何も学んでいません。作業しながら自動的に蓄積されます。',
    'memoryAdd': '追加',
    'memoryAddPlaceholder': '直接教える。例：「常に日本語で回答」',
    'memoryForget': 'これを忘れる',
    'memoryClear': 'すべて忘れる',
    'memoryClearConfirm': 'すべてのメモリを削除しますか？',
    'memoryProjectOnly': 'このプロジェクトのみ',
    'memoryStyle': '話し方',
    'memoryWorkflow': '進め方',
    'cmdAddDir': 'フォルダをもう一つ開く',
    'addFolder': 'フォルダを追加',
    'removeFolder': 'このフォルダを閉じる',
    'addedFolder': 'フォルダを追加しました',
    'addFolder_duplicate': 'そのフォルダはすでに開いています。',
    'addFolder_inside-existing': 'そのフォルダは開いているフォルダの中にあります。',
    'addFolder_contains-existing': 'そのフォルダは開いているフォルダを含んでいます — 先に閉じてください。',
    'captureWhere': 'これを記憶します — どこに入れますか？',
    'captureProject': 'このプロジェクトのみ',
    'captureUser': 'すべてのプロジェクト',
    'memoryFilesTitle': '有効な記憶ファイル',
    'memoryScope_user': 'あなた個人、全プロジェクト',
    'memoryScope_ancestor': '上位フォルダから継承',
    'memoryScope_project': 'このプロジェクト',
    'memoryNoFiles': 'まだ記憶ファイルはありません —「# ルール」で作成できます。',
    'memoryOpenHint': '/memory project または /memory user で開けます。「# 」で始めるとその場で記録します。',
    'memoryNoSuchFile': '該当する記憶ファイルがありません。',
    'memoryProject': 'このプロジェクトについて',
    'memoryLearned': '根拠',
    'memoryAddProjectPlaceholder': 'このコードベースの事実（例：純粋なロジックは src/core に置く）',
    'memoryProjectNeedsFolder': '先にフォルダを開いてください — プロジェクト記憶には対象のプロジェクトが必要です。',
    'memoryCodeIssue': '繰り返すコードの問題',
    'memoryFact': '事実',
    'memoryTitle': 'あなたについて覚えていること',
    'memoryNone': 'まだ何も覚えていません。',
    // @ mentions
    'mentionFiles': 'ファイルを添付',
    // Git
    'gitBranch': 'ブランチ',
    'gitClean': 'クリーン',
    // Web + MCP + sub-agents
    'fetchWeb': 'URL を取得',
    'searchWeb': 'ウェブ検索',
    'downloadFile': 'ダウンロード',
    'subAgent': 'サブエージェント',
    'mcpTool': 'MCP ツール',
    'mcpServers': 'MCP サーバー',
    // Skills (plugin library)
    'skills': 'スキル',
    'skillsHint': '再利用できる専門知識。関連する作業のときに自動で読み込まれます。プロジェクト単位でも全体でも配置できます。',
    'skillLibrary': 'ライブラリ',
    'skillDeploy': '配置',
    'skillProjectShort': 'プロジェクト',
    'skillDeployGlobal': 'すべてのプロジェクトに配置',
    'skillDeployProject': 'このプロジェクトのみに配置',
    'skillNeedsProject': '先にプロジェクトを開いてください。',
    'skillRemove': '削除',
    'skillEnable': '有効化',
    'skillDisable': '無効化',
    'skillDisabled': '無効',
    'skillShadowedBadge': '上書き',
    'skillShadowedTip': '同じ ID のプロジェクトスキルが、このグローバルスキルを上書きしています。',
    'skillOpen': 'SKILL.md を開く',
    'skillGlobal': '全プロジェクトで利用可',
    'skillProject': 'このプロジェクトのみ',
    'useSkill': 'スキル',
    // Custom skills
    'skillNew': '新規スキル',
    'skillEdit': '編集',
    'skillImport': 'ファイルから読み込む',
    'skillImportError': 'そのファイルは有効な SKILL.md ではありません。',
    'skillCustomBadge': 'カスタム',
    'skillCustomTip': 'あなたが作成・読み込んだものです。ConeCode は内容を検証しません。',
    'skillGlobalShort': '全プロジェクト',
    'skillExists': 'その範囲に同名のスキルが既にあります。',
    'skillNamePlaceholder': '名前（例：このリポジトリの規約）',
    'skillDescPlaceholder': 'AI はどんなときに使うべきですか？',
    'skillDescHint': '読み込む前に AI が見えるのはこの一行だけです。使うべき場面を書いてください。',
    'skillBodyPlaceholder': '実際の指示（Markdown）。すべきこと・すべきでないことを具体的に。',
    'skillNameError': '名前は必須です。',
    'skillDescError': '説明は必須です（200 文字以内）。',
    'skillBodyError': '実際の指示を書いてください（最低一文）。',
    'skillRiskTitle': 'カスタムスキルは自己責任です',
    'skillRiskBody': 'スキルは AI が従う指示であり、ファイルの編集・コマンド実行・ネットワークアクセスを指示できます。ConeCode はスキルの内容を検証しません。自分で書いたもの、または完全に信頼できるものだけを追加してください。追加した内容とその結果はすべてあなたの責任です。',
    'skillRiskStillApplies': '承認モードとコマンドサンドボックスは、スキルが実際に行う操作に引き続き適用されます。',
    'skillRiskAccept': 'リスクを理解し、責任を負います',
    'gitStatus': 'Git ステータス',
    'gitDiff': 'Git 差分',
    'thinkingTime': '思考時間',
    // Terminal
    'terminal': 'ターミナル',
    'terminals': 'ターミナル',
    'newTerminal': '新しいターミナル',
    'renameTerminal': 'ターミナル名を変更',
    // Live preview (built-in browser)
    'preview': 'プレビュー',
    'previewStart': 'プレビューを開始',
    'previewStop': '停止',
    'previewRestart': '再起動',
    'previewStarting': '起動中…',
    'previewRunning': '実行中',
    'previewIdle': '停止中',
    'previewFailed': 'プレビューを開始できません',
    'previewBack': '戻る',
    'previewForward': '進む',
    'previewStopLoading': '読み込みを中止',
    'previewOpenExternal': 'ブラウザで開く',
    'previewDesktop': 'デスクトップ',
    'previewTablet': 'タブレット',
    'previewMobile': 'スマートフォン',
    'previewLogs': '出力',
    'previewClearLogs': '出力をクリア',
    'previewNoOutput': '出力はまだありません',
    'previewNoFolder': 'プロジェクトが開かれていません',
    'previewNoFolderHint': 'フォルダを開くと、実行してここに表示できます。',
    'previewNotDetectedHint': '開発スクリプトも index.html も見つかりません。起動コマンド、またはポート番号を入力してください。',
    'previewCustomCommand': '起動コマンドを指定',
    'previewAddressPlaceholder': 'URL を入力',
    'previewNewTab': '新しいタブ',
    'previewOpen': '開く',
    'previewStaticFiles': '静的ファイル',
    'previewCommandPlaceholder': 'このプロジェクトの起動コマンド',
    'previewOrTypeUrl': '上のアドレス欄に URL を入力することもできます',
    'previewPick': '要素を選択',
    'previewPickHint': '要素をクリックするとチャットに送られます · Esc で中止',
    'previewPickedElement': 'この要素について：',
    'previewRetry': '再試行',
    'previewExited': 'プレビューのプロセスが終了しました',
    'unsaved': '未保存',
    // Computer control (the agent drives the real screen)
    'computerControl': 'パソコン操作',
    'computerActive': 'AI がマウスとキーボードを使えます',
    'computerInactive': 'オフ — AI は画面を操作できません',
    'computerUnsupported': 'パソコン操作は macOS と Windows でのみ利用できます。',
    'computerWarnTitle': 'この端末を明け渡します',
    'computerWarnBody': 'オンの間、AI は画面を見て、どこでもクリックや入力ができます（ConeCode 以外のアプリも含みます）。使い終わったらオフにしてください。',
    'computerEnable': 'AI にこのパソコンの操作を許可',
    'computerDisable': 'AI がこのパソコンを操作中',
    'computerSessionOnly': 'このセッションのみ — 起動時は常にオフ',
    'computerStopNow': '直ちに停止して操作を取り戻す',
    'computerPermissions': 'macOS の権限',
    'computerAccessibility': 'アクセシビリティ',
    'computerAccessibilityHint': 'ポインタの移動と入力に必要です。許可がないと macOS はイベントを黙って破棄します。',
    'computerScreenRecording': '画面収録',
    'computerScreenRecordingHint': 'スクリーンショットに必要です。「システム設定 › プライバシーとセキュリティ」で許可してください。',
    'computerGranted': '許可済み',
    'computerOpenSettings': '設定を開く',
    'computerRestartHint': 'macOS では、新しく許可した権限はアプリの再起動後に有効になります。',
    'computerApproval': '承認',
    'computerApprovalAsk': 'クリックやキー入力は毎回確認を求めます。続けて実行させるには承認モードを「全自動」にしてください。',
    'computerApprovalAuto': '承認モードが「全自動」のため、確認なしで実行されます。下の記録を確認してください。',
    'computerScreen': '画面',
    'computerAsSeen': '（モデルが見るサイズ）',
    'computerLastShot': 'AI が最後に見た画面',
    'computerActivity': '操作履歴',
    'computerNoActivity': 'まだ操作はありません',
    // Model auto-detect
    'detectModels': 'モデルを検出',
    'detecting': '検出中…',
    'modelsFound': '個のモデル',
    'detectFailed': '検出に失敗',
    'detectHint': 'Base URL と API キーを入力すると、利用可能なモデルとコンテキスト長を自動検出します。',
    // Changed files panel
    'panels': 'パネル',
    'panelsMore': 'その他のツール',
    'openFile': 'ファイルを開く…',
    'changedFiles': '変更ファイル',
    'filesChanged': '件のファイルを変更',
    'noChanges': '表示する変更はありません',
    // Remote control (phone)
    'remoteControl': 'リモート操作',
    'remoteDesc': 'Wi-Fi やインターネット経由でスマホから ConeCode を操作します。',
    'scanToConnect': 'スキャンして接続',
    'lanAddress': '同じ Wi-Fi 上',
    'publicLink': '公開リンク（内網穿透）',
    'startServer': '開始',
    'stopServer': '停止',
    'serverOnline': 'オンライン',
    'serverOff': 'オフ',
    'serverStarting': '起動中…',
    'tunnelStarting': 'トンネルを作成中…',
    'tunnelHint': 'cloudflared は内蔵済みで通常は設定不要です。繰り返し失敗する場合はネットワークを確認するか、ngrok（要アカウント登録と authtoken）をご利用ください。',
    'devicesConnected': '台接続中',
    'remotePassword': '接続パスワード',
    'remotePasswordPlaceholder': '任意（空欄でなし）',
    'remotePasswordHint': '設定するとパスワードは QR に埋め込まれ、スキャンで自動接続します。QR は他人に見せないでください。',
    'tunnelMethod': '公開方式',
    'tunnelCloudflare': 'Cloudflare（内蔵・アカウント不要）',
    'tunnelCustom': 'カスタムコマンド',
    'auto': '自動（最寄り）',
    'tunnelCustomHint': '{url} または {port} をプレースホルダに。コマンドは公開 https:// URL を出力する必要があります。',
    'remotePasswordReq': '6文字以上で、大文字・数字・記号を含めてください。',
    'remotePublicNeedsPassword': '公開リンクには上でパスワードの設定が必要です。',
    'tunnelNotInstalled': 'トンネルツールが見つかりません。Cloudflare は内蔵。ngrok は別途インストール（brew install ngrok 等）し authtoken を設定してください。',
    'tunnelTimeout': 'トンネル確立がタイムアウト。ネットワーク制限の可能性。再試行か方式変更を。',
    'tunnelFailed': 'トンネルの起動に失敗。下部の出力（および ~/.conecode-tunnel.log）を確認してください。',
    'ngrokHint': 'ngrok.com で authtoken を取得してください。未インストールなら下のワンクリックで。',
    'ngrokInstall': 'ngrok をワンクリックインストール',
    'cfdAdaptiveHint': 'この Mac / Windows に合う cloudflared を自動で取得します。',
    'cfdInstall': 'cloudflared をワンクリックインストール',
    'cfdInstalling': 'cloudflared をインストール中…',
    'cfdInstalled': 'cloudflared をインストールしました。公開リンクを開けます。',
    'cfdInstallFailed': 'cloudflared のインストールに失敗',
    'ngrokInstalling': 'ngrok をインストール中…',
    'ngrokInstalled': 'ngrok をインストールしました。authtoken を入力して公開リンクを開いてください。',
    'ngrokInstallFailed': 'ngrok のインストールに失敗',
    'connectedDevices': '接続中のデバイス',
    'kickDevice': '切断',
    'noDevices': '接続中のデバイスはありません。',
    'copyLink': 'リンクをコピー',
    'copied': 'コピーしました',
  },
};

interface LanguageStore {
  locale: Locale;
  t: (key: string) => string;
  setLocale: (locale: Locale) => void;
}

export const useLanguageStore = create<LanguageStore>((set, get) => ({
  locale: (localStorage.getItem('locale') as Locale) || 'en',
  t: (key: string) => translations[get().locale][key] || key,
  setLocale: (locale) => {
    localStorage.setItem('locale', locale);
    set({ locale });
  },
}));
