import { create } from 'zustand';

export type Locale = 'en' | 'zh' | 'ja';

const translations: Record<Locale, Record<string, string>> = {
  en: {
    "briefTitle": "Build something from scratch",
    "briefDescription": "Describe your idea. AI will work through the requirements and prepare a development prompt for you to review.",
    "briefIdeaLabel": "Your software idea",
    "briefPlaceholder": "What should it do, who is it for, and what matters most? Add any features, platforms, or design preferences you already have in mind.",
    "briefInputHint": "Enter to generate · Shift+Enter for a new line",
    "briefGenerate": "Think through my idea",
    "briefRegenerate": "Generate again",
    "briefThinking": "Working through requirements, edge cases, and acceptance criteria…",
    "briefOutputTitle": "Development prompt · editable",
    "briefFolderHint": "Creates a new folder under ~/ConeCode Projects/ when you start.",
    "briefFolderReuse": "Folder already open — will continue directly in it.",
    "briefFolderNew": "No folder open — a new one will be created under ~/ConeCode Projects/ on start.",
    "briefNoFolderNeeded": "No need to open a folder first — just describe your idea.",
    "briefStep1": "1 · Describe",
    "briefStep2": "2 · Review prompt",
    "briefStep3": "3 · Build",
    "briefStartInCurrent": "Start building here",
    "briefStartInNew": "Create folder & start",
    "briefOutputHint": "Enter to start · Shift+Enter to edit on a new line",
    "briefCopy": "Copy prompt",
    "briefCopied": "Copied",
    "briefStart": "Start building",
    "briefStarting": "Starting…",
    "briefGenerateFailed": "Could not generate a complete prompt. Check your model connection and try again.",
    "briefFolderFailed": "Could not create or open the project folder. Check folder permissions and retry.",
    "briefConversationChanged": "You switched conversations while preparing the project. Return here to start again.",
    "briefStartFailed": "Could not start the project. Your prompt is still available to copy or retry.",
    "briefCopyFailed": "Copy failed. Select the prompt and copy it manually.",
    // Sidebar
    'newChat': 'New Chat',
    'newChatInFolder': 'New chat here',
    'conversations': 'Conversations',
    'files': 'Files',
    'noFolderGroup': 'No folder',
    'chatsCount': 'chats',
    'sidebarNoProject': 'No project',
    'sidebarFiles': 'Files',
    'installHolding': 'Installing — model paused, will continue when done',
    'installContinue': 'Installs finished. Activate and continue the work you were doing.',
    'settings': 'Settings',
    'language': 'Language',
    // Chat
    'typeMessage': 'Type a message...',
    // Agent home ("find me something to do")
    'homeGreetingMorning': 'Morning — what should we work on?',
    'homeGreetingAfternoon': 'Afternoon — what should we work on?',
    'homeGreetingEvening': 'Evening — what should we work on?',
    'homeGreetingNight': 'Still up? What should we work on?',
    'homeClean': 'clean tree',
    'homeFiles': 'files',
    'homeScripts': 'scripts',
    'homeRescan': 'Re-read the project',
    'homeNoFolder': 'No folder open yet',
    'homeUncommitted': 'uncommitted',
    'homeNoTests': 'no tests',
    'homeFindWork': 'Work I found for you',
    'homeFindWorkAction': 'Find work',
    'homeRefindWork': 'Find again',
    'homeFindFailed': 'Could not work out what to do',
    'homeIdleTitle': 'Let me look through the project',
    'homeIdleBody': 'I will read the git state, TODO comments, tests and scripts, then propose concrete tasks you can start with one click.',
    'homeOpenFolderTitle': 'Open a project first',
    'homeOpenFolderBody': 'Once a folder is open I can read its state and suggest what to do next — or scaffold a brand-new project for you.',
    'homeResume': 'Pick up where you left off',
    'homeContinue': 'Continue',
    'homeOpenOnly': 'Just open',
    'homeOpenTodos': 'left to do',
    'homeStartNew': 'Start something new',
    // The recommended next action
    'recLabel': 'Do this next',
    'recResume': 'Finish what you started — items still open:',
    'recReview': 'Review your uncommitted changes — files changed:',
    'recTask': 'Start the top task I found:',
    'recTests': 'This project has no tests — add the first one',
    'recTestsPrompt': 'This project has no tests. Pick the most important behaviour, set up the project\'s standard test runner if it is missing, and write one real test for it. Run it and show me it passes.',
    'recStart': 'Open a project, or pick one below and I will build it',
    'recStartNew': 'Everything is clean — pick something new to build',
    'recDialogInputAria': 'Next action message',
    'recDialogPlaceholder': 'Edit the suggested instruction, or write your own. Enter to start.',
    'recDialogStartPlaceholder': 'Describe what to build, or leave empty to pick a project below…',
    'recDialogHint': 'Enter to start · Shift+Enter for a new line',
    'recDialogSend': 'Start',
    'recDialogBrowseIdeas': 'Browse ideas',
    // Autopilot
    'autopilotTitle': 'Pick one — I build it',
    'autopilotSubtitle': 'folder, code, tests, all on my own',
    'autopilotThinking': 'thinking of ideas…',
    'autopilotFrom': 'ideas from',
    'autopilotMore': 'Other ideas',
    'autopilotMedium': 'bigger',
    'autopilotCreating': 'Creating the project folder',
    'autopilotBuilding': 'Building it',
    'autopilotVerifying': 'Running it to check it works',
    'autopilotRepairing': 'Fixing what failed',
    'autopilotRepairingHint': 'It did not pass yet — fixing and re-running. Attempt',
    'autopilotDone': 'Done and verified',
    'autopilotDoneHint': 'The project was built and its tests pass.',
    'autopilotOpenReadme': 'Open README',
    'autopilotFailed': 'Could not finish',
    'autopilotFailedHint': 'It still does not pass after several attempts. The conversation has the full history — tell it what to do next.',
    'autopilotNoVerify': 'It never reported a command to verify the project with.',
    'autopilotNoFolder': 'Could not create the project folder.',
    'homeNewProject': 'New project',
    'homeNewProjectDesc': 'Describe an idea and I will scaffold it, working, with a test.',
    'homeNewProjectHint': 'Describe what you want to build. I will pick the stack, scaffold it, and prove it runs.',
    'homeNewProjectPlaceholder': 'e.g. a CLI that watches a folder and compresses new images',
    'homeNewProjectNeedsDir': 'I will ask you where to put it.',
    'homeCreate': 'Build it',
    'homeOpenFolderDesc': 'Work on code that already exists.',
    'homeExplore': 'Explore this codebase',
    'homeExploreDesc': 'Get an architecture tour of what is here.',
    'homeExplorePrompt': 'Give me a tour of this codebase: what it does, how it is structured, the entry points, and the three things I most need to know before editing it. Read enough of the real files to be accurate.',
    'homeReview': 'Review my changes',
    'homeReviewDesc': 'Check the uncommitted work for problems.',
    'homeReviewPrompt': 'Review my uncommitted changes with git status and git diff. Look for real defects, edge cases and inconsistencies with the surrounding code, and tell me what you would fix first. Do not change anything yet.',
    'justNow': 'just now',
    'minutesAgoShort': 'm ago',
    'hoursAgoShort': 'h ago',
    'daysAgoShort': 'd ago',
    'taskKind_bug': 'Bug',
    'taskKind_feature': 'Feature',
    'taskKind_refactor': 'Refactor',
    'taskKind_test': 'Tests',
    'taskKind_docs': 'Docs',
    'taskKind_chore': 'Chore',
    'taskEffort_quick': 'Quick',
    'taskEffort_medium': 'Medium',
    'taskEffort_large': 'Large',
    'taskRisk_low': 'low risk',
    'taskRisk_medium': 'some risk',
    'taskRisk_high': 'risky',
    'selectModelHint': 'Select a model and type a message',
    'dismiss': 'Dismiss',
    'ai': 'AI',
    // Model Selector
    'searchModels': 'Search models...',
    'selectModel': 'Select Model',
    'noModels': 'No models found',
    'favorites': 'Favorites',
    'recent': 'Recent',
    // Model Tooltip
    'textChat': 'Text Chat',
    'vision': 'Vision',
    'imageGen': 'Image Gen',
    'audioIn': 'Audio In',
    'audioOut': 'Audio Out',
    'functions': 'Functions',
    'context': 'Context',
    'maxOutput': 'Max Output',
    'contextWindow': 'Context Window',
    'editLimits': 'Edit limits',
    'readFromApi': 'Read from API',
    'reset': 'Reset',
    // Context Meter
    'contextUsage': 'Context Usage',
    'contextLeft': 'context left',
    'used': 'Used',
    'remaining': 'Remaining',
    'compactions': 'Compactions',
    'tokens': 'tokens',
    'messages': 'Messages',
    'attachedFiles': 'Attached files',
    'systemPrompt': 'System prompt',
    'estimated': 'estimated',
    'attachFiles': 'Attach files',
    // Provider Settings
    'providerSettings': 'Provider Settings',
    'setGeneral': 'General',
    'setGeneralDesc': 'How much the agent may do on its own, and how it is confined.',
    'setProviders': 'Providers',
    'setProvidersDesc': 'API endpoints and keys. Detect a provider\'s models after entering its URL and key.',
    'setMcpDesc': 'Connect MCP servers to give the agent extra tools.',
    'addProvider': 'Add Provider',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'cancel': 'Cancel',
    'save': 'Save',
    'cannotPreview': 'Cannot preview this file',
    'delete': 'Delete',
    'providerName': 'Provider Name',
    'baseUrl': 'Base URL',
    'apiKey': 'API Key',
    'defaultModel': 'Default Model',
    'timeout': 'Timeout (ms)',
    'default': 'Default',
    'none': 'None',
    'custom': 'Custom',
    'openFolder': 'Open Folder',
    'closeFolder': 'Close Folder',
    'closeFile': 'Close File',
    'closeOthers': 'Close others',
    'closeAll': 'Close all',
    'copyPath': 'Copy path',
    'copyRelativePath': 'Copy relative path',
    'explorerFilter': 'Filter files...',
    'explorerMore': 'More actions',
    'newFile': 'New file',
    'newFolder': 'New folder',
    'renameFailed': 'Rename failed. Check the name and try again.',
    'createFailed': 'Create failed. Check the name and permissions.',
    'deleteConfirm': 'Delete {name}? This cannot be undone.',
    'deleteFailed': 'Delete failed. Check permissions and try again.',
    'collapseAll': 'Collapse all',
    'replace': 'Replace',
    'findPrev': 'Previous match',
    'findNext': 'Next match',
    'matchCase': 'Match case',
    'replaceOne': 'Replace',
    'replaceAll': 'All',
    'toggleReplace': 'Toggle replace',
    'goToLine': 'Go',
    'goToLinePlaceholder': 'Line 1-{max}',
    'linesCount': '{n} lines',
    'spaces': 'spaces',
    'aiChanges': 'AI changes',
    'aiChangesShort': 'AI',
    'clearAiMarks': 'Clear AI highlight',
    'clear': 'Clear',
    'refresh': 'Refresh',
    'enableReasoning': 'Enable Reasoning',
    'disableReasoning': 'Disable Reasoning',
    'lightMode': 'Light Mode',
    'darkMode': 'Dark Mode',
    'reasoning': 'Reasoning',
    // Code Review
    'codeReview': 'Code Review',
    'pending': 'pending',
    'applied': 'Applied',
    'reverted': 'Reverted',
    'pendingChanges': 'Pending Changes',
    'appliedChanges': 'Applied Changes',
    'revertedChanges': 'Reverted Changes',
    'apply': 'Apply',
    'reject': 'Reject',
    'applyAll': 'Apply all',
    'rejectAll': 'Reject all',
    'autoApproveAll': 'Auto-approve all (experimental)',
    'autoApproveWarning': 'Risky: the AI will run commands and apply file changes automatically, without asking for your confirmation.',
    'errNoContent': 'The model returned no content. It may have only produced reasoning, or the response was cut off. Try retrying, lowering thinking effort, or raising the model\'s max output tokens.',
    'errTruncated': 'The model hit its max output token limit before finishing (often truncated mid-reasoning). Raise the model\'s max output tokens or lower the thinking effort, then retry.',
    'revert': 'Revert',
    'revertFailed': 'Revert failed',
    'close': 'Close',
    'commandExecution': 'Command Execution',
    'pendingApproval': 'Pending Approval',
    'reviewCommand': 'Review',
    'workingDirectory': 'Working directory',
    'commandApprovalHint': 'Check the command and working directory before running it. Its effects may not be reversible.',
    'commandFailed': 'The command failed.',
    'changeFailed': 'Failed',
    'from': 'From:',
    'to': 'To:',
    'source': 'Source:',
    'destination': 'Destination:',
    'result': 'Result:',
    'execute': 'Execute',
    'read': 'Read',
    'list': 'List',
    'search': 'Search',
    'find': 'Find',
    'edit': 'Edit',
    'send': 'Send',
    'editMessagePlaceholder': 'Edit message...',
    'create': 'Create',
    'rename': 'Rename',
    'copy': 'Copy',
    'run': 'Run',
    'openApp': 'Open app',
    'open': 'Open',
    'systemInfo': 'System info',
    'question': 'Question',
    'thinking': 'Thinking',
    'writing': 'Writing',
    // Message bubble
    'toolResult': 'Tool result',
    'you': 'You',
    'aiAsking': 'AI is asking',
    'typeAnswerHint': 'Type your answer in the input below and send',
    'answered': 'Answered',
    // Chat input send hints
    'sendHintEnter': 'Enter to send · Shift+Enter for newline',
    'sendHintCmd': 'Cmd/Ctrl+Enter to send',
    // Thinking effort levels
    'effortFast': 'Fast',
    'effortAuto': 'Auto · picks depth from your ask',
    'previewAnnotate': 'Pin a spot for precise edit',
    'previewAnnotateHint': 'Click the page to pin coordinates · fills the chat',
    'previewAnnotateClear': 'Clear pins',
    'modePlan': 'Plan',
    'modeTask': 'Task',
    'modeOrchestrate': 'Orchestrate',
    'modeRsi': 'RSI',
    'modeMenu': 'Modes & extras',
    'effortBalanced': 'Balanced',
    'effortDeep': 'Deep',
    // Slash commands
    'commandsTitle': 'Commands',
    'cmdHelp': 'Show available commands',
    'cmdClear': 'Start a new chat',
    'cmdCompact': 'Summarize & free up context',
    'cmdPlan': 'Toggle Plan Mode (read-only planning)',
    'cmdGoal': 'Start or replace a long-running goal',
    'cmdMode': 'Set agent mode: standard | goal | orchestrate | rsi',
    'agentModeStandard': 'Standard (default)',
    'agentModeStandardHint': 'Default coding loop — one request, end to end.',
    'agentModeGoal': 'Goal',
    'agentModeGoalHint': 'Long-running goal pursuit until external completion checks pass.',
    'agentModeOrchestrate': 'Orchestrate',
    'agentModeOrchestrateHint': 'Conductor + sub-agents: decompose, research in parallel, integrate.',
    'agentModeRsi': 'RSI+RL',
    'agentModeRsiHint': 'RL-style search toward the frozen goal: sample, score with an orchestrated judge panel, accept only if reward beats best, stop at plateau.',
    'cmdReview': 'Review Git changes without modifying them',
    'cmdWorktree': 'Manage isolated Git worktrees',
    'cmdInit': 'Analyze the project and write AGENTS.md',
    'cmdAgents': 'Open the AGENTS.md project memory',
    'cmdModel': 'Switch model',
    'cmdMemory': 'Show what I remember about you',
    'cmdDiff': 'Summarize the current git diff',
    'cmdCommit': 'Stage changes and commit',
    'helpTitle': 'ConeCode commands',
    'helpProjectCommands': 'Project commands',
    'noAgentsMd': 'No AGENTS.md found yet — run /init to create one.',
    'goalRunning': 'Goal running',
    'goalPaused': 'Goal paused',
    'pauseGoal': 'Pause goal',
    'resumeGoal': 'Resume goal',
    'editGoal': 'Edit goal',
    'clearGoal': 'Clear goal',
    'goalResumePrompt': 'Resume the active goal. Re-check current progress and continue until its completion criteria are verified.',
    'goalUpdatedPrompt': 'The active goal has been updated. Use this as the new completion criteria:',
    'reviewReadOnly': 'Prioritized findings · read-only',
    'reviewUncommitted': 'Review uncommitted changes',
    'reviewUncommittedHint': 'Includes staged, unstaged, and untracked paths in the current checkout.',
    'reviewBase': 'Review against a base branch',
    'reviewBaseHint': 'Reviews the branch diff from the merge base to HEAD.',
    'reviewCommit': 'Review a commit',
    'reviewCommitHint': 'Reviews exactly one commit by SHA, tag, or revision.',
    'reviewCommitPlaceholder': 'Commit SHA or revision',
    'reviewNeedsRepo': 'Open a project inside a Git repository to start a review.',
    'reviewReadFailed': 'Could not read the selected Git change set.',
    'reviewNoChanges': 'There are no changes in this review scope.',
    'reviewPreparing': 'Preparing review…',
    'startReview': 'Start read-only review',
    'worktrees': 'Worktrees',
    'worktreesHint': 'Run parallel tasks in isolated Git checkouts.',
    'worktreeName': 'Task name (optional)',
    'createWorktree': 'Create isolated worktree',
    'worktreeNeedsRepo': 'Open a Git repository to use worktrees.',
    'worktreeLoadFailed': 'Could not load Git worktrees.',
    'worktreeCreateFailed': 'Could not create the worktree.',
    'worktreeOpenFailed': 'Could not open the worktree folder.',
    'worktreeRemoveFailed': 'Could not remove the worktree.',
    'detachedHead': 'Detached HEAD',
    'current': 'Current',
    'localCheckout': 'primary checkout',
    'uncommitted': 'uncommitted',
    'removeWorktreeConfirm': 'Remove this clean managed worktree?',
    'compacting': 'Compacting…',
    'contextCompacted': 'Context compacted',
    'compactFailed': 'Could not compact the conversation.',
    'compact': 'Compact',
    'showCompacted': 'Show compacted messages',
    'hideCompacted': 'Hide compacted messages',
    // Plan mode
    'planMode': 'Plan Mode',
    'plan': 'Plan',
    'planModeHint': 'Read-only — the agent researches and proposes a plan before editing.',
    'presentPlan': 'Plan ready',
    'approvePlan': 'Approve & run',
    'keepPlanning': 'Keep planning',
    'planApproved': 'Plan approved — implement it now.',
    'planBlocked': 'Blocked in Plan Mode (read-only). Present a plan instead.',
    // To-dos
    'todos': 'To-dos',
    'todoUpdated': 'To-do list updated.',
    'deleteTodo': 'Remove this item',
    'clearTodos': 'Clear the checklist',
    'expandTodos': 'Show the full checklist',
    'collapseTodos': 'Hide the full checklist',
    'allTodosCompleted': 'All tasks completed',
    // Rollback
    'undoChange': 'Undo change',
    'undoChangeConfirmTitle': 'Undo only this workspace change?',
    'undoChangeKeepsChat': 'The conversation stays. The agent will be told that the workspace changed.',
    'rollbackConversation': 'Roll back chat',
    'checkpointRollbackTitle': 'Roll back to this conversation checkpoint?',
    'checkpointRollbackChat': 'This message and everything after it will be removed; reversible file changes will be restored.',
    'checkpointExternalEffects': 'Executed commands and computer actions remain in effect and stay marked as applied.',
    'confirmCheckpointRollback': 'Roll back checkpoint',
    'checkpointUnavailable': 'This change has no conversation checkpoint.',
    // Approval modes
    'approvalMode': 'Approval',
    'approvalSuggest': 'Suggest',
    'approvalAutoEdit': 'Auto-edit',
    'approvalFullAuto': 'Full-auto',
    'approvalSuggestDesc': 'Ask before every edit and command (safest).',
    'approvalAutoEditDesc': 'Auto-apply file edits; ask before running commands.',
    'approvalFullAutoDesc': 'Auto-apply edits and run commands without asking (risky).',
    // Tool-call protocol
    'toolCallMode': 'Tool calls',
    'toolModeAuto': 'Auto',
    'toolModeNative': 'Native',
    'toolModePrompt': 'Prompt',
    'toolModeAutoDesc': 'Use the provider\'s function calling when the model supports it (recommended).',
    'toolModeNativeDesc': 'Always send tool schemas — for endpoints that support tools but don\'t advertise them.',
    'toolModePromptDesc': 'Never send tool schemas; ask for ```json actions in the prompt instead.',
    'callingTool': 'Calling',
    // Command sandbox
    'sandbox': 'Command sandbox',
    'sandboxOn': 'Confined',
    'sandboxOff': 'Unrestricted',
    'sandboxOnDesc': 'Commands can read your machine and only write inside the workspace (and temp). Recommended.',
    'sandboxOffDesc': 'Commands run with your full permissions and can modify anything on this machine.',
    'sandboxNetwork': 'Allow network access (needed for installs)',
    'sandboxUnavailable': 'Command sandboxing is only available on macOS; commands run unrestricted here.',
    'notifications': 'Notifications',
    'notificationsDesc': 'Get an OS notification when a task finishes or needs attention.',
    'notification_never': 'Never',
    'notification_background': 'In background',
    'notification_always': 'Always',
    'notifyApprovals': 'Notify when an action needs approval',
    'preventSleepWhileRunning': 'Prevent app suspension while a task is running',
    'taskReadyTitle': 'Task ready',
    'taskReadyBody': 'ConeCode finished the current turn.',
    'approvalReadyTitle': 'Approval needed',
    'approvalReadyBody': 'ConeCode is waiting for you to review an action.',
    // Memory
    'memory': 'Memory',
    'memoryEnabled': 'On',
    'memoryHint': 'What ConeCode has learned: how you want work done, what is true about this project, and how you like to be talked to. Applied to every new conversation.',
    'memoryEmpty': 'Nothing learned yet. Memories are picked up automatically as you work.',
    'memoryAdd': 'Add',
    'memoryAddPlaceholder': 'Teach it something, e.g. "Always answer in Chinese"',
    'memoryForget': 'Forget this',
    'memoryClear': 'Forget everything',
    'memoryClearConfirm': 'Delete all memories?',
    'memoryProjectOnly': 'this project',
    'memoryStyle': 'Communication style',
    'memoryWorkflow': 'How to work',
    'cmdAddDir': 'Open another folder alongside this one',
    'addFolder': 'Add folder',
    'removeFolder': 'Close this folder',
    'addedFolder': 'Folder added',
    'addFolder_duplicate': 'That folder is already open.',
    'addFolder_inside-existing': 'That folder is already inside an open one.',
    'addFolder_contains-existing': 'That folder contains folders that are already open — close them first.',
    'captureWhere': 'Remember this — where does it belong?',
    'captureProject': 'This project',
    'captureUser': 'Every project',
    'memoryFilesTitle': 'Memory files in effect',
    'memoryScope_user': 'yours, every project',
    'memoryScope_ancestor': 'inherited from a parent folder',
    'memoryScope_project': 'this project',
    'memoryNoFiles': 'No memory files yet — start one with "# your rule".',
    'memoryOpenHint': 'Open one with /memory project or /memory user. Capture a new rule by starting a message with "# ".',
    'memoryNoSuchFile': 'No memory file matches that.',
    'memoryProject': 'About this project',
    'memoryLearned': 'learned',
    'memoryAddProjectPlaceholder': 'A fact about this codebase, e.g. "Pure logic lives in src/core"',
    'memoryProjectNeedsFolder': 'Open a folder first — a project memory needs a project to belong to.',
    'memoryCodeIssue': 'Recurring code problem',
    'memoryFact': 'Fact',
    'memoryTitle': 'What I remember about you',
    'memoryNone': 'I have not learned anything about you yet.',
    // @ mentions
    'mentionFiles': 'Attach a file',
    // Git
    'gitBranch': 'Branch',
    'gitClean': 'clean',
    // Web + MCP + sub-agents
    'fetchWeb': 'Fetch URL',
    'searchWeb': 'Web search',
    'downloadFile': 'Download',
    'subAgent': 'Sub-agent',
    'mcpTool': 'MCP tool',
    'mcpServers': 'MCP Servers',
    // Skills (plugin library)
    'skills': 'Skills',
    'skillsHint': 'Reusable expertise the agent loads when a task calls for it. Deploy one to this project or to every project.',
    'skillLibrary': 'Library',
    'skillDeploy': 'Deploy',
    'skillProjectShort': 'Project',
    'skillDeployGlobal': 'Deploy for every project',
    'skillDeployProject': 'Deploy to this project only',
    'skillNeedsProject': 'Open a project first to deploy a skill into it.',
    'skillRemove': 'Remove',
    'skillEnable': 'Enable',
    'skillDisable': 'Disable',
    'skillDisabled': 'disabled',
    'skillShadowedBadge': 'overridden',
    'skillShadowedTip': 'A project skill with the same id overrides this global skill.',
    'skillOpen': 'Open SKILL.md',
    'skillGlobal': 'Available in every project',
    'skillProject': 'This project only',
    'useSkill': 'Skill',
    // Custom skills
    'skillNew': 'New skill',
    'skillEdit': 'Edit',
    'skillImport': 'Import file',
    'skillImportError': 'That file is not a usable SKILL.md.',
    'skillCustomBadge': 'custom',
    'skillCustomTip': 'You wrote or imported this. ConeCode does not review custom skills.',
    'skillGlobalShort': 'All projects',
    'skillExists': 'A skill with this name already exists in that scope.',
    'skillNamePlaceholder': 'Name, e.g. House Style',
    'skillDescPlaceholder': 'When should the AI use this?',
    'skillDescHint': 'This one line is all the AI sees until it decides to load the skill — say when to use it.',
    'skillBodyPlaceholder': 'The instructions. Markdown. Be specific about what to do and what not to do.',
    'skillNameError': 'A name is required.',
    'skillDescError': 'A description is required (max 200 characters).',
    'skillBodyError': 'Write the actual instructions (at least a sentence).',
    'skillRiskTitle': 'Custom skills run on your responsibility',
    'skillRiskBody': 'A skill is instructions the AI will follow, and it can tell the AI to edit files, run commands, or fetch from the network. ConeCode does not review or sandbox the text of a skill. Only install skills you wrote or fully trust — anything you add here, and whatever comes of it, is on you.',
    'skillRiskStillApplies': 'Your approval mode and the command sandbox still apply to anything a skill actually does.',
    'skillRiskAccept': 'I understand — I accept responsibility',
    'gitStatus': 'Git status',
    'gitDiff': 'Git diff',
    'thinkingTime': 'Thinking time',
    // Terminal
    'terminal': 'Terminal',
    'terminals': 'Terminals',
    'newTerminal': 'New terminal',
    'renameTerminal': 'Rename terminal',
    // Live preview (built-in browser)
    'preview': 'Preview',
    'previewStart': 'Start preview',
    'previewStop': 'Stop',
    'previewRestart': 'Restart',
    'previewStarting': 'Starting…',
    'previewRunning': 'Running',
    'previewIdle': 'Not running',
    'previewFailed': 'Preview failed',
    'previewBack': 'Back',
    'previewForward': 'Forward',
    'previewStopLoading': 'Stop loading',
    'previewOpenExternal': 'Open in browser',
    'previewDesktop': 'Desktop',
    'previewTablet': 'Tablet',
    'previewMobile': 'Phone',
    'previewLogs': 'Output',
    'previewClearLogs': 'Clear output',
    'previewNoOutput': 'No output yet',
    'previewNoFolder': 'No project open',
    'previewNoFolderHint': 'Open a folder and I can run it and show the result right here.',
    'previewNotDetectedHint': 'No dev script or index.html found. Type the command that starts this project, or a port to open.',
    'previewCustomCommand': 'Custom command',
    'previewAddressPlaceholder': 'Type a URL',
    'previewNewTab': 'New tab',
    'previewOpen': 'Open',
    'previewStaticFiles': 'Static files',
    'previewCommandPlaceholder': 'Command that starts this project',
    'previewOrTypeUrl': 'Or type any address above',
    'previewPick': 'Pick an element',
    'previewPickHint': 'Click any element to send it to the chat · Esc to cancel',
    'previewPickedElement': 'About this element:',
    'previewRetry': 'Retry',
    'previewExited': 'The preview process exited',
    'unsaved': 'Unsaved',
    // Computer control (the agent drives the real screen)
    'computerControl': 'Computer control',
    'computerActive': 'The agent can use your mouse and keyboard',
    'computerInactive': 'Off — the agent cannot touch the screen',
    'computerUnsupported': 'Computer control is only available on macOS and Windows.',
    'computerWarnTitle': 'This hands over your machine',
    'computerWarnBody': 'While this is on, the agent can see your screen and click and type anywhere — including apps that are not ConeCode. Turn it off when you are done.',
    'computerEnable': 'Let the agent control this computer',
    'computerDisable': 'Agent is controlling this computer',
    'computerSessionOnly': 'For this session only — always off at launch',
    'computerStopNow': 'Stop and take back control',
    'computerPermissions': 'macOS permissions',
    'computerAccessibility': 'Accessibility',
    'computerAccessibilityHint': 'Needed to move the pointer and type. Without it macOS discards the events silently.',
    'computerScreenRecording': 'Screen Recording',
    'computerScreenRecordingHint': 'Needed to take screenshots. Grant it in System Settings › Privacy & Security.',
    'computerGranted': 'Granted',
    'computerOpenSettings': 'Open Settings',
    'computerRestartHint': 'macOS only applies a newly granted permission after the app restarts.',
    'computerApproval': 'Approval',
    'computerApprovalAsk': 'Each click and keystroke is shown for your approval first. Switch the approval mode to Full auto to let them run unattended.',
    'computerApprovalAuto': 'Approval mode is Full auto, so actions run without asking. Watch the log below.',
    'computerScreen': 'Screen',
    'computerAsSeen': 'as the model sees it',
    'computerLastShot': 'What the agent last saw',
    'computerActivity': 'Activity',
    'computerNoActivity': 'Nothing yet',
    // Model auto-detect
    'detectModels': 'Detect models',
    'detecting': 'Detecting…',
    'modelsFound': 'models detected',
    'detectFailed': 'Detection failed',
    'detectHint': 'Enter Base URL + API Key, then auto-detect available models and their context windows.',
    // Changed files panel
    'panels': 'Panels',
    'panelsMore': 'More tools',
    'openFile': 'Open file…',
    'changedFiles': 'Changed files',
    'filesChanged': 'files changed',
    'noChanges': 'No changes to show',
    // Remote control (phone)
    'remoteControl': 'Remote control',
    'remoteDesc': 'Drive ConeCode from your phone over Wi-Fi or the internet.',
    'scanToConnect': 'Scan to connect',
    'lanAddress': 'On the same Wi-Fi',
    'publicLink': 'Public link (内网穿透)',
    'startServer': 'Start',
    'stopServer': 'Stop',
    'serverOnline': 'Online',
    'serverOff': 'Off',
    'serverStarting': 'Starting…',
    'tunnelStarting': 'Opening tunnel…',
    'tunnelHint': 'cloudflared is built in, so this usually needs no setup. If it keeps failing, check your network, or use ngrok (needs a free account + authtoken).',
    'devicesConnected': 'connected',
    'remotePassword': 'Password',
    'remotePasswordPlaceholder': 'Optional — leave blank for none',
    'remotePasswordHint': 'When set, the password is embedded in the QR so scanning connects automatically. Keep the QR private.',
    'tunnelMethod': 'Tunnel method',
    'tunnelCloudflare': 'Cloudflare (built-in, no account)',
    'tunnelCustom': 'Custom command',
    'auto': 'Auto (nearest)',
    'tunnelCustomHint': 'Use {url} or {port} as placeholders; the command must print a public https:// URL.',
    'remotePasswordReq': 'Must be ≥6 chars with an uppercase letter, a number, and a symbol.',
    'remotePublicNeedsPassword': 'Set a password above to enable the public link.',
    'tunnelNotInstalled': 'Tunnel tool not found. Cloudflare is built in; ngrok must be installed (e.g. brew install ngrok) and given an authtoken.',
    'tunnelTimeout': 'Timed out establishing the tunnel — the network may block it. Retry or switch method.',
    'tunnelFailed': 'The tunnel failed to start. See the tool output below (and ~/.conecode-tunnel.log).',
    'ngrokHint': 'Get a free authtoken at ngrok.com. No ngrok installed? Use the one-click install below.',
    'ngrokInstall': 'One-click install ngrok',
    'cfdAdaptiveHint': 'Downloads the matching cloudflared for this computer (macOS / Windows) automatically.',
    'cfdInstall': 'One-click install cloudflared',
    'cfdInstalling': 'Installing cloudflared…',
    'cfdInstalled': 'cloudflared installed. Open the public link.',
    'cfdInstallFailed': 'cloudflared install failed',
    'ngrokInstalling': 'Installing ngrok…',
    'ngrokInstalled': 'ngrok installed. Fill the authtoken and open the public link.',
    'ngrokInstallFailed': 'ngrok install failed',
    'connectedDevices': 'Connected devices',
    'kickDevice': 'Kick',
    'noDevices': 'No devices connected.',
    'copyLink': 'Copy link',
    'copied': 'Copied',
  },
  zh: {
    // Agent home ("找点活干")
    // The recommended next action
    // Autopilot
    // Slash commands
    // Plan mode
    // To-dos
    // Rollback
    // Approval modes
    // Tool-call protocol
    // Command sandbox
    // Memory
    // @ mentions
    // Git
    // Web + MCP + sub-agents
    // Skills (plugin library)
    // Custom skills
    // Terminal
    // Live preview (built-in browser)
    // Computer control (the agent drives the real screen)
    // Model auto-detect
    // Changed files panel
    // Remote control (phone)
  },
  ja: {
    // Agent home
    // The recommended next action
    // Autopilot
    // Slash commands
    // Plan mode
    // To-dos
    // Rollback
    // Approval modes
    // Tool-call protocol
    // Command sandbox
    // Memory
    // @ mentions
    // Git
    // Web + MCP + sub-agents
    // Skills (plugin library)
    // Custom skills
    // Terminal
    // Live preview (built-in browser)
    // Computer control (the agent drives the real screen)
    // Model auto-detect
    // Changed files panel
    // Remote control (phone)
  },
};

interface LanguageStore {
  locale: Locale;
  t: (key: string) => string;
  setLocale: (locale: Locale) => void;
}

export const useLanguageStore = create<LanguageStore>((set, get) => ({
  locale: (localStorage.getItem('locale') as Locale) || 'en',
  t: (key: string) => translations[get().locale][key] || key,
  setLocale: (locale) => {
    localStorage.setItem('locale', locale);
    set({ locale });
  },
}));
